(function(g){var window=this;'use strict';var ePS=function(G,X,Q){g.F(function(R){G.N=g.PT(X,Q);g.rX(R)})},wM=function(G){G.isActive()||G.start()},r3n=function(G,X){return X?G.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},a84=function(G){return g.sB(G)||G.G("web_enable_caption_language_preference_stickiness")},EV3=function(G,X){var Q=new g.VT;
Q.languageCode=G.languageCode;Q.languageName=G.languageName;Q.name=G.name;Q.displayName=G.displayName;Q.kind=G.kind;Q.isDefault=!1;Q.N=G.N;Q.isTranslateable=G.isTranslateable;Q.vssId=G.vssId;Q.url=G.url;Q.translationLanguage=X;G.xtags&&(Q.xtags=G.xtags);G.captionId&&(Q.captionId=G.captionId);return Q},xm4=function(G,X){var Q,R,S;
return g.F(function(Z){if(Z.W==1)return Q=G+"|"+X,g.l(Z,g.NT(),2);if(Z.W!=3){R=Z.N;if(!R)throw g.MT("gct");return g.l(Z,g.Q1(R),3)}S=Z.N;return Z.return(S.get("captions",Q))})},OOa=function(G,X,Q){xm4(G,X).then(function(R){R&&Q(R.trackData,new g.VT(R.metadata))})},gVG=function(G){if(!zPZ.test(G))throw Error("'"+G+"' is not a valid hex color");
G.length==4&&(G=G.replace(c3G,"#$1$1$2$2$3$3"));G=G.toLowerCase();G=parseInt(G.slice(1),16);return[G>>16,G>>8&255,G&255]},UmL=function(){var G=void 0;
G=G===void 0?{}:G;var X="suggest_correction"in g.isn?g.isn.suggest_correction:"Edit caption";X=X||"";var Q={},R;for(R in G){Q={d_:Q.d_};Q.d_=R;var S=function(Z){return function(){return String(G[Z.d_])}}(Q);
X=X.replace(new RegExp("\\$\\{"+Q.d_+"\\}","gi"),S);X=X.replace(new RegExp("\\$"+Q.d_,"gi"),S)}return X},l8a=function(){return g.xL("yt-player-caption-display-settings")},hy=function(){this.segments=[]},B73=function(G,X){var Q=g.fa(G.segments,X);
Q>=0||Q<0&&(-Q-1)%2===1||(Q=-Q-1,Q>0&&X-G.segments[Q-1]===1&&Q<G.segments.length&&G.segments[Q]-X===1?(g.ad(G.segments,Q),g.ad(G.segments,Q-1)):Q>0&&X-G.segments[Q-1]===1?G.segments[Q-1]=X:Q<G.segments.length&&G.segments[Q]-X===1?G.segments[Q]=X:(g.Wn(G.segments,Q,0,X),g.Wn(G.segments,Q+1,0,X)))},FHv=function(G,X,Q,R,S,Z){g.I.call(this);
this.policy=G;this.player=X;this.AT=Q;this.T=R;this.C=S;this.j=Z;this.V=new hy;this.S=-1;this.Y=this.W=this.N=null;this.yH=0;this.J=new g.fU(this.nB,1E3,this);this.events=new g.KP(this);g.d(this,this.J);g.d(this,this.events);this.events.B(X,"SEEK_COMPLETE",this.jM);this.jM();this.nB()},CZG=function(G){return G.N&&G.N.S?G.N.S+G.player.q9()<G.player.getCurrentTime():!1},ton=function(G,X){if(G.policy.gt&&G.player.lA()){var Q=g.h1(X,G.policy,{});
Q.set("pot",G.player.lA());Q=Q.Rt()}else Q=g.h1(X,G.policy,{}).Rt();var R={format:"RAW",withCredentials:!0};if(G.policy.QH){R.method="POST";var S=X.V;S&&Object.keys(S).length>0?R.postBody=g.N2(S,g.gP):R.postBody=(0,g.Fs)([120,0])}G.C&&(R.responseType="arraybuffer");var Z=++G.yH,H=(0,g.TB)();G.Y=g.eg(Q,R,3,100,-1,function(w){w.errorCode==="net.timeout"&&G.player.Ni("capnt",{rn:Z++})}).then(function(w){if(G.policy.zp&&Z%100===1){var h=(0,g.TB)();
G.player.Ni("caprsp",{rn:Z,ms:h-H,kb:(w.xhr.responseText.length/1024).toFixed()})}a:{w=w.xhr;G.U_();if(G.W){var L=!(G.C?w.response:w.responseText)||w.status>=400;if(h=g.QTS(w)){w=g.h1(G.W,G.policy,{});G.W.hX(w,h);ton(G,G.W);break a}if(L)G.player.Ni("capfail",{status:w.status});else{var k;g.GZ("fcb_r",(0,g.TB)(),((k=G.player.getVideoData())==null?void 0:k.AT)||"");k=G.W.LO[0].oU;G.T!=null&&G.S!==k&&(h=G.W.LO[0],G.C?G.T(w.response,(h.startTime+G.player.q9())*1E3):G.T(w.responseText,(h.startTime+G.player.q9())*
1E3),G.S=k)}}G.W=null;G.Y=null}}).EG(function(w){G.W=null;
G.Y=null;var h;G.player.Ni("capfail",{rn:Z,status:(h=w.xhr)==null?void 0:h.status})});
G.W=X;B73(G.V,G.W.LO[0].oU)},L8=function(G,X){g.TK.call(this,X);
this.N=G;this.U=X;this.V=null;this.S=!1;this.logger=new g.sp("caps");this.J=g.ZWw(this.U,this.N)},I8H=function(G,X){var Q=[],R;
for(R in G.N.N)if(G.N.N.hasOwnProperty(R)){var S=G.N.N[R];if(g.eu(S,X||null)){var Z=S.info.id,H=Z,w="."+Z,h="",L="";if(S=S.info.captionTrack)Z=S.languageCode,H=S.displayName,w=S.vssId,h=S.kind,L=S.id;else{S=Z;var k=g.ruS.get(S);k==null&&(k=Voo[S]||Voo[S.replace(/-/g,"_")],g.ruS.set(S,k));S=k;H=S||H}Q.push(new g.VT({id:R,languageCode:Z,languageName:H,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:w,kind:h,captionId:L}))}}return Q},dmG=function(G,X){return X!=null&&X in G.N.N?G.N.N[X]:null},
WHo=function(G,X,Q){var R=[],S;
for(S in G.N.N)if(G.N.N.hasOwnProperty(S)){var Z=G.N.N[S];if(g.eu(Z,Q||null)){var H=Z.info.captionTrack;H&&H.languageCode===X&&R.push(Z)}}return R.length?R[0]:null},kd=function(G,X,Q,R,S,Z,H,w,h,L){var k=L.isInline()&&!0,Y={};
Object.assign(Y,X);Object.assign(Y,G.params);Object.assign(Y,Q);var M={};Object.assign(M,X.t1);G.params.t1&&Object.assign(M,G.params.t1);Object.assign(M,Q.t1);k&&(Y.windowOpacity=.6,M.backgroundOpacity=0);Y.t1=M;var m=Y.Cv===1,u=[{D:"span",X:"captions-text",L:{style:"word-wrap: normal; display: block;"}}],r,x,c;(w=w.TT("caption_edit_on_hover")&&((r=L.getVideoData().getPlayerResponse())==null?void 0:(x=r.captions)==null?void 0:(c=x.playerCaptionsTracklistRenderer)==null?void 0:c.openTranscriptCommand))&&
u.unshift({D:"button",X:"caption-edit",L:{tabindex:"0","aria-label":UmL()},K:[{D:"svg",L:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},K:[{D:"path",L:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.f.call(this,{D:"div",X:"caption-window",L:{id:"caption-window-"+G.id,dir:m?"rtl":"ltr",tabindex:"0",lang:Y.lang},K:u});var z=
this;this.J=[];this.Mi=!1;this.W=G;this.IU=this.QH=null;this.R6=Z;this.f7=H;this.T=null;this.maxWidth=Z*.96;this.maxHeight=H*.96;this.N=Y;this.F7=Q;this.yH=X;this.V=this.VH("captions-text");this.Hs=this.V.style.getPropertyValue("box-decoration-break")!==""||this.V.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.CO=pbk(R,S,Z,H);this.Js=h;w&&(this.S=this.VH("caption-edit"),this.B(this.S,"click",function(){z.Js()}));
this.type=0;this.wb=this.CO*y3H(M);this.bB=k;G=new g.Fo(this.element,!0);g.d(this,G);G.subscribe("dragstart",this.ew,this);G.subscribe("dragmove",this.cj,this);G.subscribe("dragend",this.Jl,this);this.cM=this.Xm=this.KO=this.BM=0;G="";this.N.windowOpacity&&(G=gVG(this.N.windowColor),G="rgba("+G[0]+","+G[1]+","+G[2]+","+this.N.windowOpacity+")");X={"background-color":G,display:this.N.isVisible===!1?"none":"","text-align":f8d[this.N.textAlign]};this.Hs&&(X["border-radius"]=G?this.wb/8+"px":"");(this.Y=
this.W.params.Cv===2||this.W.params.Cv===3)&&Dmd(this,this.element);g.DN(this.element,X);if(k){var B;(B=this.element.parentElement)==null||B.style.setProperty("--caption-window-color",G)}switch(this.N.rV){case 0:case 1:case 2:g.Gk(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Gk(this.element,"ytp-caption-window-bottom")}},Dmd=function(G,X){var Q="vertical-rl";
G.N.Og===1&&(Q="vertical-lr");g.wC&&(Q=Q==="vertical-lr"?"tb-lr":"tb-rl");g.DN(X,"-o-writing-mode",Q);g.DN(X,"-webkit-writing-mode",Q);g.DN(X,"writing-mode",Q);g.DN(X,"text-orientation","upright");g.Gk(X,"ytp-vertical-caption");G.W.params.Cv===3&&(g.DN(X,"text-orientation",""),g.DN(X,"transform","rotate(180deg)"))},y3H=function(G){var X=1+.25*(G.fontSizeIncrement||0);
if(G.offset===0||G.offset===2)X*=.8;return X},N7o=function(G,X){var Q={},R=X.background?X.background:G.N.t1.background;
if(X.backgroundOpacity!=null||X.background){var S=X.backgroundOpacity!=null?X.backgroundOpacity:G.N.t1.backgroundOpacity;R=gVG(R);Q.background="rgba("+R[0]+","+R[1]+","+R[2]+","+S+")";G.Hs&&(Q["box-decoration-break"]="clone",Q["border-radius"]=G.wb/8+"px")}if(X.fontSizeIncrement!=null||X.offset!=null)Q["font-size"]=G.CO*y3H(X)+"px";R=1;S=X.color||G.N.t1.color;if(X.color||X.textOpacity!=null)S=gVG(S),R=X.textOpacity==null?G.N.t1.textOpacity:X.textOpacity,S="rgba("+S[0]+","+S[1]+","+S[2]+","+R+")",
Q.color=S,Q.fill=S;var Z=X.charEdgeStyle;Z===0&&(Z=void 0);if(Z){S="rgba(34, 34, 34, "+R+")";var H="rgba(204, 204, 204, "+R+")";X.kd&&(H=S=X.kd);var w=G.CO/16/2,h=Math.max(w,1),L=Math.max(2*w,1),k=Math.max(3*w,1),Y=Math.max(5*w,1);R=[];switch(Z){case 4:for(;k<=Y;k+=w)R.push(L+"px "+L+"px "+k+"px "+S);break;case 1:L=window.devicePixelRatio>=2?.5:1;for(Z=h;Z<=k;Z+=L)R.push(Z+"px "+Z+"px "+S);break;case 2:R.push(h+"px "+h+"px "+H);R.push("-"+h+"px -"+h+"px "+S);break;case 3:for(k=0;k<5;k++)R.push("0 0 "+
L+"px "+S)}Q["text-shadow"]=R.join(", ")}S="";switch(X.fontFamily){case 1:S='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:S='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:S='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:S='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:S='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:S=g.V9()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:S='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}S&&(Q["font-family"]=S);S=X.offset;S==null&&(S=G.N.t1.offset);switch(S){case 0:Q["vertical-align"]="sub";break;case 2:Q["vertical-align"]="super"}X.fontFamily===7&&(Q["font-variant"]="small-caps");X.bold&&(Q["font-weight"]="bold");X.italic&&(Q["font-style"]="italic");X.underline&&(Q["text-decoration"]=
"underline");X.D0&&(Q.visibility="hidden");X.eF===1&&G.Y&&(Q["text-combine-upright"]="all",Q["text-orientation"]="mixed",S=g.rS||g.Y_,G.W.params.Cv===3?Q.transform=S?"rotate(90deg)":"rotate(180deg)":S&&(Q.transform="rotate(-90deg)"));if(X.textEmphasis===1||X.textEmphasis===2||X.textEmphasis===3||X.textEmphasis===4||X.textEmphasis===5)if(g.rS)Q["font-weight"]="bold";else switch(Q["text-emphasis-style"]="filled circle",Q["text-emphasis-color"]="currentcolor",Q["webkit-text-emphasis"]="filled circle",
X.textEmphasis){case 4:case 3:Q["text-emphasis-position"]="under left";Q["webkit-text-emphasis-position"]="under left";break;case 5:case 2:Q["text-emphasis-position"]="over right",Q["webkit-text-emphasis-position"]="over right"}return Q},Yd=function(G){G=G.split("px");
return G.length>0?(G=Number(G[0]))?G:0:0},A3H=function(G){G.T=g.ml("SPAN");
g.DN(G.T,{display:"block"});g.Gk(G.T,"caption-visual-line");G.V.appendChild(G.T)},nVH=function(G,X){var Q=g.ml("SPAN");
g.DN(Q,{display:"inline-block","white-space":"pre-wrap"});g.DN(Q,N7o(G,X));Q.classList.add("ytp-caption-segment");G.T.appendChild(Q);Q.previousElementSibling&&(g.DN(Q.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.DN(Q,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return Q},$mV=function(G,X,Q){G.Mi=G.Mi||!!Q;
var R={};Object.assign(R,G.N.t1);Object.assign(R,Q||X.N);Object.assign(R,G.F7.t1);(Q=!G.T)&&A3H(G);for(var S=G.QH&&G.IU&&g.oB(R,G.IU)?G.QH:nVH(G,R),Z=typeof X.text==="string",H=Z?X.text.split("\n"):[X.text],w=0;w<H.length;w++){var h=w>0||!X.append,L=H[w];h&&!Q?(A3H(G),S=nVH(G,R)):h&&Q&&(Q=!1);L&&(S.appendChild(Z?g.oL(L):L),Z||L.tagName!=="RUBY"||L.childElementCount!==4||g.rS||!g.Aj(L.children[2],"text-emphasis")||(h=G.Y?"padding-right":"padding-top",g.Aj(L.children[2],"text-emphasis-position")&&(h=
G.Y?"padding-left":"padding-bottom"),g.kh?g.DN(S,h,"1em"):g.DN(S,h,"0.5em")))}G.IU=R;G.QH=S;G.J.push(X)},pbk=function(G,X,Q,R){var S=X/360*16;
X>=G&&(G=640,R>Q*1.3&&(G=480),S=Q/G*16);return S},vV4=function(){this.Y=this.time=this.mode=this.W=0;
this.V=new bOd(this);this.C=new bOd(this);this.N=[];this.clear()},iOV=function(G,X,Q){if(G===255&&X===255||!G&&!X)return{EL:G,
gk:X,result:0};G=J3O[G];X=J3O[X];if(G&128){var R;if(R=!(X&128))R=X,R=Q.eG()&&Q.gk===R;if(R)return{EL:G,gk:X,result:1}}else if(X&128&&1<=G&&G<=31)return{EL:G,gk:X,result:2};return{EL:G,gk:X,result:3}},XiO=function(G,X,Q,R){X===255&&Q===255||!X&&!Q?(++G.Y===45&&G.reset(),G.V.W.clear(),G.C.W.clear()):(G.Y=0,G2V(G.V,X,Q,R))},QnG=function(G,X){G.N.sort(function(S,Z){var H=S.time-Z.time;
return H===0?S.order-Z.order:H});
for(var Q=g.e(G.N),R=Q.next();!R.done;R=Q.next())R=R.value,G.time=R.time,R.type===0?XiO(G,R.aT,R.IT,X):R.type===1&&G.W&496&&G2V(G.C,R.aT,R.IT,X);G.N.length=0},jH=function(){this.type=0},M_=function(){this.state=this.gk=this.EL=0},R0S=function(){this.timestamp=this.N=0},m1=function(G){this.C=G;
this.Y=[];this.N=this.W=this.row=0;this.style=new jH;for(G=this.V=0;G<=15;G++){this.Y[G]=[];for(var X=0;X<=32;X++)this.Y[G][X]=new R0S}},o4=function(G,X){if(G.style.type===3){for(var Q=0,R=0,S=G.C.time+0,Z="",H="",w=S,h=1;h<=15;++h){for(var L=!1,k=R?R:1;k<=32;++k){var Y=G.Y[h][k];
if(Y.N!==0){Q===0&&(Q=h,R=k);L=String.fromCharCode(Y.N);var M=Y.timestamp;M<S&&(S=M);Y.timestamp=w;H&&(Z+=H,H="");Z+=L;L=!0}if((Y.N===0||k===32)&&L){H="\n";break}else if(R&&!L)break}if(Q&&!L)break}Z&&X.V(Q,R,S,w,Z)}else for(R=Q=0,Z=S=G.C.time+0,H=1;H<=15;++H)for(w="",h=1;h<=32;++h)if(k=G.Y[H][h],Y=k.N,Y!==0&&(Q===0&&(Q=H,R=h),L=String.fromCharCode(Y),M=k.timestamp,M<=S&&(S=M),w+=L,k.reset()),h===32||Y===0)w&&X.V(Q,R,S,Z,w),S=Z,w="",R=Q=0},wi4=function(G,X){switch(G){case 0:return SxS[(X&127)-32];
case 1:return Z0v[X&15];case 2:return H0O[X&31];case 3:return qxG[X&31]}return 0},uR=function(G){return G.Y[G.row][G.W]},P7=function(G,X,Q){X>=2&&G.W>1&&(--G.W,uR(G).N=0);
var R=uR(G);R.timestamp=G.C.time+0;R.N=wi4(X,Q);G.W<32&&G.W++},h0n=function(G,X,Q,R){for(var S=0;S<R;S++)for(var Z=0;Z<=32;Z++){var H=G.Y[X+S][Z],w=G.Y[Q+S][Z];
H.N=w.N;H.timestamp=w.timestamp}},TF=function(G,X,Q){for(var R=0;R<Q;R++)for(var S=0;S<=32;S++)G.Y[X+R][S].reset()},LNd=function(G){G.row=G.N>0?G.N:1;
G.W=1;TF(G,0,15)},k2v=function(G){this.Y=G;
this.C=0;this.style=new jH;this.S=new m1(this.Y);this.J=new m1(this.Y);this.text=new m1(this.Y);this.W=this.S;this.V=this.J;this.N=this.W},YxH=function(G,X,Q){var R=G.W,S=!1;
switch(G.style.get()){case 4:case 1:case 2:G.style.get()===4&&R.N>0||(o4(R,Q),LNd(G.W),LNd(G.V),R.row=15,R.N=X,S=!0)}G.style.set(3);G.N=R;G.N.style=G.style;G.Y.mode=1<<R.V;S?R.W=1:R.N!==X&&(R.N>X?(o4(R,Q),TF(R,R.row-R.N,X)):R.row<X&&(X=R.N),R.N=X)},jnH=function(G){G.style.set(1);
G.N=G.V;G.N.N=0;G.N.style=G.style;G.Y.mode=1<<G.N.V},M5S=function(G){G.style.set(4);
G.N=G.text;G.N.style=G.style;G.Y.mode=1<<G.N.V},bOd=function(G){this.N=G;
this.C=0;this.Y=new k2v(this.N);this.S=new k2v(this.N);this.W=new M_;this.V=this.Y},G2V=function(G,X,Q,R){G.W.update();
X=iOV(X,Q,G.W);switch(X.result){case 0:return;case 1:case 2:return}var S=X.EL;Q=X.gk;if(32<=S||!S)G.N.mode&G.N.W&&(X=S,X&128&&(X=127),Q&128&&(Q=127),G=G.V.N,X&96&&P7(G,0,X),Q&96&&P7(G,0,Q),X!==0&&Q!==0&&G.style.type===3&&o4(G,R));else if(S&16)a:if(!G.W.matches(S,Q)&&(X=G.W,X.EL=S,X.gk=Q,X.state=2,X=S&8?G.S:G.Y,G.V=X,G.N.mode=1<<(G.C<<2)+(X.C<<1)+(X.style.type===4?1:0),(G.N.mode|1<<(G.C<<2)+(X.C<<1)+(X.style.type!==4?1:0))&G.N.W))if(Q&64){R=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(S&7)<<1|Q>>5&1];
G=Q&16?((Q&14)>>1)*4:0;Q=X.N;switch(X.style.get()){case 4:R=Q.row;break;case 3:if(R!==Q.row){if(R<Q.N&&(R=Q.N,R===Q.row))break;var Z=1+Q.row-Q.N,H=1+R-Q.N;h0n(Q,H,Z,Q.N);X=Z;S=Q.N;H<Z?(Z=H+S-Z,Z>0&&(X+=Z,S-=Z)):(Z=Z+S-H,Z>0&&(S-=Z));TF(Q,X,S)}}Q.row=R;Q.W=G+1}else switch(S&7){case 1:switch(Q&112){case 32:P7(X.N,0,32);break a;case 48:Q===57?(R=X.N,uR(R).N=0,R.W<32&&R.W++):P7(X.N,1,Q&15)}break;case 2:Q&32&&P7(X.N,2,Q&31);break;case 3:Q&32&&P7(X.N,3,Q&31);break;case 4:case 5:if(32<=Q&&Q<=47)switch(Q){case 32:jnH(X);
break;case 33:R=X.N;R.W>1&&(--R.W,uR(R).N=0);break;case 36:R=X.N;X=uR(R);for(G=0;G<=15;G++)for(Q=0;Q<=32;Q++)if(R.Y[G][Q]===X){for(;Q<=32;Q++)R.Y[G][Q].reset();break}break;case 37:YxH(X,2,R);break;case 38:YxH(X,3,R);break;case 39:YxH(X,4,R);break;case 40:P7(X.N,0,32);break;case 41:X.style.set(2);X.N=X.W;X.N.N=0;X.N.style=X.style;X.Y.mode=1<<X.N.V;break;case 42:R=X.text;R.N=15;R.style.set(4);LNd(R);M5S(X);break;case 43:M5S(X);break;case 44:G=X.W;switch(X.style.get()){case 1:case 2:case 3:o4(G,R)}TF(G,
0,15);break;case 45:b:{G=X.N;switch(X.style.get()){default:case 2:case 1:break b;case 4:if(G.row<15){++G.row;G.W=1;break b}break;case 3:}G.N<2&&(G.N=2,G.row<G.N&&(G.row=G.N));X=G.row-G.N+1;o4(G,R);h0n(G,X,X+1,G.N-1);TF(G,G.row,1)}break;case 46:TF(X.V,0,15);break;case 47:o4(X.W,R),X.V.updateTime(X.Y.time+0),R=X.V,X.V=X.W,X.W=R,jnH(X)}break;case 7:switch(Q){case 33:case 34:case 35:R=X.N,(R.W+=Q&3)>32&&(R.W=32)}}},mEv=function(){},K8=function(G,X,Q,R,S,Z,H){Z=Z===void 0?!1:Z;
H=H===void 0?null:H;g.yG.call(this,G,G+X,{priority:Q,namespace:"captions"});this.windowId=R;this.text=S;this.append=Z;this.N=H},ubO=function(G,X,Q,R,S,Z,H){var w=Z[0],h=H[w.getAttribute("p")];
if(h.VG===1){var L=Z[1],k=Z[2];Z=Z[3];w.getAttribute("t");L.getAttribute("t");k.getAttribute("t");Z.getAttribute("t");w.getAttribute("p");L.getAttribute("p");Z.getAttribute("p");H=H[k.getAttribute("p")];w=oaa(w.textContent,L.textContent,k.textContent,Z.textContent,H);return new K8(G,X,S,Q,w,R,h)}switch(h.VG){case 9:case 10:h.textEmphasis=1;break;case 11:h.textEmphasis=2;break;case 12:h.textEmphasis=3;break;case 13:h.textEmphasis=4;break;case 14:h.textEmphasis=5}return new K8(G,X,S,Q,w.textContent||
"",R,h)},oaa=function(G,X,Q,R,S){var Z=g.V9(),H=Z?g.ml("DIV"):g.ml("RUBY"),w=g.ml("SPAN");
w.textContent=G;H.appendChild(w);G=Z?g.ml("DIV"):g.ml("RP");G.textContent=X;H.appendChild(G);X=Z?g.ml("DIV"):g.ml("RT");X.textContent=Q;H.appendChild(X);Q=S.VG;if(Q===10||Q===11||Q===12||Q===13||Q===14)if(g.DN(X,"text-emphasis-style","filled circle"),g.DN(X,"text-emphasis-color","currentcolor"),g.DN(X,"webkit-text-emphasis","filled circle"),S.VG===11||S.VG===13)g.DN(X,"webkit-text-emphasis-position","under left"),g.DN(X,"text-emphasis-position","under left");Q=!0;if(S.VG===4||S.VG===7||S.VG===12||
S.VG===14)g.DN(H,"ruby-position","over"),g.DN(H,"-webkit-ruby-position","before");else if(S.VG===5||S.VG===6||S.VG===11||S.VG===13)g.DN(H,"ruby-position","under"),g.DN(H,"-webkit-ruby-position","after"),Q=!1;S=Z?g.ml("DIV"):g.ml("RP");S.textContent=R;H.appendChild(S);Z&&(R=Q,g.DN(H,{display:"inline-block",position:"relative"}),Z=H.firstElementChild.nextElementSibling,g.DN(Z,"display","none"),Z=Z.nextElementSibling,g.DN(Z,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.DN(H.lastElementChild,"display","none"),R?(g.DN(H,"padding-top","0.6em"),g.DN(Z,"top","0")):(g.DN(H,"padding-bottom","0.6em"),g.DN(Z,"bottom","0")));return H},eH=function(){g.I.apply(this,arguments)},rM=function(G,X,Q,R,S){g.yG.call(this,G,G+X,{priority:Q,
namespace:"captions"});this.id=R;this.params=S;this.N=[]},Pzo=function(G){var X="_"+a4++;
return new rM(0,0x8000000000000,0,X,G)},Es=function(G){eH.call(this);
this.V=G;this.pens={};this.T={};this.j={};this.C="_"+a4++;this.J={};this.W=this.N=null;this.S=!0},xd=function(G,X){G=G.getAttribute(X);
if(G!=null)return Number(G)},Os=function(G,X){G=G.getAttribute(X);
if(G!=null)return G==="1"},zF=function(G,X){G=xd(G,X);
return G!==void 0?G:null},gM=function(G,X){G=G.getAttribute(X);
if(G!=null)return c7.test(G),G},snd=function(G,X){var Q={},R=X.getAttribute("ws");
Object.assign(Q,R?G.j[R]:G.V);G=zF(X,"mh");G!=null&&(Q.Eo=G);G=zF(X,"ju");G!=null&&(Q.textAlign=G);G=zF(X,"pd");G!=null&&(Q.Cv=G);G=zF(X,"sd");G!=null&&(Q.Og=G);G=gM(X,"wfc");G!=null&&(Q.windowColor=G);X=xd(X,"wfo");X!==void 0&&(Q.windowOpacity=X/255);return Q},Te3=function(G,X){var Q={},R=X.getAttribute("wp");
R&&Object.assign(Q,G.T[R]);G=zF(X,"ap");G!=null&&(Q.rV=G);G=xd(X,"cc");G!=null&&(Q.AD=G);G=xd(X,"ah");G!=null&&(Q.D1=G);G=xd(X,"rc");G!=null&&(Q.D8=G);X=xd(X,"av");X!=null&&(Q.dK=X);return Q},KNa=function(G,X,Q,R){var S={};
Object.assign(S,Te3(G,X));Object.assign(S,snd(G,X));R?g.oB(S,G.V)?(R=G.C,S=G.V):R="_"+a4++:R=X.getAttribute("id")||"_"+a4++;G=xd(X,"t")+Q;X=xd(X,"d")||0x8000000000000;if(S.Cv===2||S.Cv===3)Q=S.D8,S.D8=S.AD,S.AD=Q;return new rM(G,X,0,R,S)},Us=function(G){eH.call(this);
this.S=G;this.N=new Map;this.V=new Map;this.C=new Map;this.W=new Map},lR=function(G){G=g.pT(Math.round(G),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-G.length)+G},e0d=function(G,X,Q,R,S){R===0&&(R=0x8000000000000);
var Z={};X.wpWinPosId&&Object.assign(Z,G.V.get(X.wpWinPosId));X.wsWinStyleId&&Object.assign(Z,G.C.get(X.wsWinStyleId));G=X.rcRowCount;G!==void 0&&(Z.D8=G);X=X.ccColCount;X!==void 0&&(Z.AD=X);if(Z.Cv===2||Z.Cv===3)X=Z.D8,Z.D8=Z.AD,Z.AD=X;return new rM(Q,R,0,S,Z)},B7=function(G,X,Q){g.TK.call(this,G);
this.videoData=X;this.audioTrack=Q;this.C=X.AF},F8=function(G,X,Q,R,S,Z,H,w,h,L){kd.call(this,G,X,Q,R,S,Z,H,w,h,L);
this.type=1},C8=function(G,X,Q){this.trackData=G;
this.S=Q;this.version=this.C=this.Y=this.byteOffset=0;this.W=[];this.N=new DataView(this.trackData)},ty=function(G){var X=G.byteOffset;
G.byteOffset+=1;return G.N.getUint8(X)},Vw=function(G){var X=G.byteOffset;
G.byteOffset+=4;return G.N.getUint32(X)},I4=function(G,X){eH.call(this);
this.W=G;this.V=X;this.track=this.V.languageName==="CC3"?4:0;this.N=new vV4;this.N.W=1<<this.track},aWH=function(G){if(typeof G==="string")return!1;
G=new C8(G,8,0);return rNL(G)},rNL=function(G){if(!(G.byteOffset<G.N.byteLength)||Vw(G)!==1380139777)return!1;
G.version=ty(G);if(G.version>1)return!1;ty(G);ty(G);ty(G);return!0},dM=function(G,X,Q,R,S,Z,H,w,h,L){kd.call(this,G,X,Q,R,S,Z,H,w,h,L);
var k=this;this.type=2;this.Yc=[];this.AT=this.j=this.SA=0;this.DC=NaN;this.As=0;this.C7=null;this.N9=new g.fU(this.w4,433,this);this.S&&(L.createClientVe(this.S,this,167342),this.B(this.S,"click",function(){L.logClick(k.S)}),G=new g.Fo(this.element,!0),g.d(this,G),G.subscribe("hoverstart",function(){L.logVisibility(k.S,!0)},this));
g.Gk(this.element,"ytp-caption-window-rollup");g.d(this,this.N9);g.DN(this.element,"overflow","hidden")},Eaa=function(G,X){if(!X)return"";
G.Y&&G.W.params.Og!==1&&(X*=-1);return"translate"+(G.Y?"X":"Y")+"("+X+"px)"},xEv=function(G){G.Yc=Array.from(G.element.getElementsByClassName("caption-visual-line"));
for(var X=G.W.params.D8,Q=0,R=0,S=G.Yc.length-1;Q<X&&S>-1;){var Z=G.Yc[S];R+=G.Y?Z.offsetWidth:Z.offsetHeight;Q++;S--}G.j=R;X=Math;Q=X.max;isNaN(G.DC)&&((R=G.N.AD)?(S=g.ml("SPAN"),g.ee(S,"\u2013".repeat(R)),g.DN(S,N7o(G,G.N.t1)),G.V.appendChild(S),G.DC=S.offsetWidth,G.V.removeChild(S)):G.DC=0);R=G.V;G.AT=Q.call(X,G.DC,G.As,(G.Y?R.offsetHeight:R.offsetWidth)+1)},O0O=function(G,X){xEv(G);
var Q=G.Yc.reduce(function(Z,H){return(G.Y?H.offsetWidth:H.offsetHeight)+Z},0);
Q=G.j-Q;if(Q!==G.SA){var R=Q>0&&G.SA===0,S=Q<G.SA;X||isNaN(Q)||R||!S||(g.Gk(G.element,"ytp-rollup-mode"),G.B(G.element,"transitionend",G.w4));g.DN(G.V,"transform",Eaa(G,Q));G.SA=Q}xEv(G)},z0S=function(G,X,Q,R){var S=this;
this.U=G;this.Y=X;this.logger=Q;this.IW=R;this.u9=[];this.Uj=[];this.N=null;this.gh={l3c:function(){return S.N},
wL:function(){return S.u9}};
G=g.i2(this.U.Z().experiments,"html5_override_micro_discontinuities_threshold_ms");this.W=G>0?G:10},UEv=function(G,X){G.N=function(Q,R){if(Q.info.V){var S=Q;
if(G.Uj.length>0){for(S=G.Uj.shift();G.Uj.length>0;)S=g.r0(S,G.Uj.shift());S=g.r0(S,Q)}if(S){Q=S;try{var Z=g.aW(Q)*1E3}catch(L){Z=Q.info.startTime*1E3}try{var H=g.NPT(Q)*1E3}catch(L){H=Q.info.duration*1E3}if(Z<0||H<0)Z<0&&(Z=Q.info.startTime*1E3),H<0&&(H=Q.info.duration*1E3);Q.info.startTime=Z/1E3;Q.info.C=Z/1E3;Q.info.duration=H/1E3;Q.info.T=H/1E3;Z=G.nJ(S);H=Z.oU;Z={formatId:Z.formatId,startTimeMs:Z.startTimeMs,durationMs:Z.durationMs,tN:H,tE:H};H=cN3(G.u9,Z.startTimeMs);var w=(Q=H>=0?G.u9[H]:null)?
Q.startTimeMs+Q.durationMs:0,h=Z.startTimeMs+Z.durationMs;!Q||Z.startTimeMs-w>G.W?G.u9.splice(H+1,0,Z):(Q.durationMs=Math.max(w,h)-Q.startTimeMs,Q.tE=Math.max(Q.tE,Z.tE));R(G.u9);R=g.eK(S);ga4(G.Y,R.buffer.slice(R.byteOffset,R.byteLength+R.byteOffset),X,S.info.C)}else G.logger.N(350058965,"Empty slice")}else G.Uj.push(Q)};
G.U.addEventListener("sabrCaptionsDataLoaded",G.N)},cN3=function(G,X){G=g.fa(G,{startTimeMs:X},function(Q,R){return Q.startTimeMs-R.startTimeMs});
return G>=0?G:-G-2},W7=function(G,X){g.TK.call(this,X);
this.N=G;this.U=X;this.logger=new g.sp("caps");this.V=this.S=null;this.J=new z0S(this.U,this,this.logger,this.N.IW)},ga4=function(G,X,Q,R){G.logger.debug(function(){return"SABR captions data received for "+R});
G.S?G.V==null?G.logger.N(350058965,"Null loaded track meta data at captions data received"):Q.h0(X,G.V,R*1E3):G.logger.N(350058965,"Null Representation at captions data received")},lWa=function(G,X){var Q=[],R;
for(R in G.N.N)if(G.N.N.hasOwnProperty(R)){var S=G.N.N[R];if(g.eu(S,X||null)){var Z=S.info.id,H=Z,w="."+Z,h="",L="";if(S=S.info.captionTrack)Z=S.languageCode,H=S.displayName,w=S.vssId,h=S.kind,L=S.id;Q.push(new g.VT({id:R,languageCode:Z,languageName:H,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:w,kind:h,captionId:L}))}}return Q},Beo=function(G,X,Q){var R=[],S;
for(S in G.N.N)if(G.N.N.hasOwnProperty(S)){var Z=G.N.N[S];if(g.eu(Z,Q||null)){var H=Z.info.captionTrack;H&&H.languageCode===X&&R.push(Z)}}return R.length?R[0]:null},FNL=function(G,X){if(!g.Dh7(G)||G.N!=null&&g.ZWw(X,G.N)&&G.N.N.rawcc!=null)return!1;
X=!!G.N&&G.N.isManifestless&&Object.values(G.N.N).some(function(Q){return g.eu(Q,"386")});
G=!!G.N&&!G.N.isManifestless&&g.HFl(G.N);return X||G},Czn=function(){eH.call(this)},V5G=function(G){var X=t5S.length;
if(G.byteLength<X)return!1;G=new Uint8Array(G,0,X);for(var Q=0;Q<X;Q++)if(t5S[Q]!==G[Q])return!1;return!0},IWV=function(G,X,Q,R,S,Z,H,w,h){switch(H.tagName){case "b":w.bold=!0;
break;case "i":w.italic=!0;break;case "u":w.underline=!0}for(var L=0;L<H.childNodes.length;L++){var k=H.childNodes[L];if(k.nodeType===3)k=new K8(X,Q,R,S.id,k.nodeValue,Z||L>0,g.Mn(w)?void 0:w),h.push(k),S.N.push(k);else{var Y={};Object.assign(Y,w);IWV(G,X,Q,R,S,!0,k,Y,h)}}},dE4=function(G){var X=G.split(":");
G=0;X=g.e(X);for(var Q=X.next();!Q.done;Q=X.next())G=G*60+Number(Q.value);return G*1E3},WNZ=function(G,X,Q,R){R=Object.assign({Eo:0},R);
return new rM(G,X,Q,"_"+a4++,R)},p8=function(G,X){g.I.call(this);
this.U=G;this.tT=X;this.N=null;this.W=this.U.ST();this.logger=new g.sp("caps")},yNZ=function(G,X,Q){if(typeof X==="string"||aWH(X))return[{trackData:X,
ir:Q}];if(typeof X==="string"&&X.substring(0,6)==="WEBVTT"||typeof X!=="string"&&V5G(X))return[{trackData:X,ir:Q}];var R=new DataView(X);if(R.byteLength<=8||R.getUint32(4)!==1718909296)return[];var S=g.nyC(R);if(G.W&&S){var Z=g.dUX(S),H=g.WMl(S);S=S.qW;Z&&S&&G.W.Zt(S,Z,H)}G=g.Kf(R,1835295092);if(!G||!G.length||!G[0].size)return[];Z=[];for(H=0;H<G.length;H++)S=G[H],S=new Uint8Array(X,S.dataOffset,S.size-(S.dataOffset-S.offset)),S=g.jx(S),Z.push({trackData:S,ir:Q+H*1E3});pin(R,Z,Q);return Z=Z.filter(function(w){return!!w.trackData})},
pin=function(G,X,Q){var R=g.YX(G,0,1836476516),S=9E4;
R&&(S=g.j4(R)||9E4);R=0;for(var Z=g.Kf(G,1836019558),H=0;H<Z.length;H++){var w=Z[H];H<X.length&&(w=g.YX(G,w.dataOffset,1953653094))&&(w=g.YX(G,w.dataOffset,1952867444))&&(w=g.sP(w)/S*1E3,H===0&&(R=w),X[H].ir=w-R+Q||Q*H*1E3)}},fWk=function(G,X,Q){G.N||(G.N=new Czn);
G=G.N.Y(X,Q);Math.random()<.01&&g.EL(Error("Deprecated subtitles format in web player: WebVTT"));return G},DEL=function(G){var X={};
if(G=g.WM(G))X.lang=G,g.UqO.test(G)&&(X.Cv=1);return X},naH=function(G){g.P6.call(this,G);
var X=this;this.U=G;this.QH=[];this.Yc={};this.wb={};this.T=!1;this.V="NONE";this.N=this.j=this.AT=this.CO=this.BM=null;this.N9={lF:function(){X.lF()},
h0:function(Z,H,w,h){X.h0(Z,H,w,h)}};
this.W=null;this.tT=this.U.Z();this.videoData=this.U.getVideoData();this.KO=this.U.mp();this.Y={t1:{}};this.S={t1:{}};g.MY(this.videoData)?this.V="OFFLINE":FNL(this.videoData,this.U)?this.V="SABR_LIVE":g.HWV(this.videoData,this.U)?this.V="LIVE":this.videoData.captionTracks.length?this.V="INNERTUBE":this.videoData.Mj&&(this.V="TTS");this.Xm=this.tT.controlsType==="3";this.cM=new p8(this.U,this.tT);this.Mi=new g.KP(this);this.J=new g.f({D:"div",X:"ytp-caption-window-container",L:{id:"ytp-caption-window-container"}});
this.yH={top:0,right:0,bottom:0,left:0,width:1,height:1};var Q=null,R=g.gC("yt-html5-player-modules::subtitlesModuleData");R&&(Q=new g.Kd(R));this.storage=Q;var S;this.bB=!((S=G.EY())==null||!S.RH());this.C=Ne4(this);this.DC=!this.C&&this.Xm&&this.bB&&(this.V==="LIVE"||this.V==="SABR_LIVE");g.d(this,this.cM);this.C?this.SA=this.IU=null:(this.IU=new g.yK(this.hP,void 0,this),g.d(this,this.IU),this.SA=new g.fU(this.CLi,2E3,this),g.d(this,this.SA));g.d(this,this.Mi);g.$6(this.player,this.J.element,4);
g.d(this,this.J);this.C||this.Mi.B(G,"resize",this.t9);(this.As=g.RI(this.tT)&&!g.LZ()&&!this.U.isFullscreen()&&!this.C&&!this.DC)&&this.Mi.B(G,"resize",this.GaA);this.Mi.B(G,"onPlaybackAudioChange",this.miC);this.Mi.B(G,g.Dy("captions"),function(Z){X.onCueRangeEnter(Z)});
this.Mi.B(G,g.N3("captions"),function(Z){X.onCueRangeExit(Z)});
ANd(this,l8a()||{});this.player.tS("onCaptionsModuleAvailable")},va4=function(G){if(G.tT.Ti===1||G.videoData.qU===1||g.DI(G.videoData,"yt:cc")==="alwayson")return!0;
if(G.videoData.captionTracks.length)var X=G.getAudioTrack().W;if(G.tT.Ti===2){if(g.sB(G.tT))var Q=$Ea(G);else if(G.storage)try{Q=G.storage.get("module-enabled")}catch(S){G.storage.remove("module-enabled")}else Q=null;if(Q!=null)return!!Q}Q=r3n(G.player.getAudioTrack(),g.sB(G.tT));var R=g.DI(G.videoData,"yt:cc");if(b0L(G)===void 0){if(Q==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return R?R==="on":!0;if(Q==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return R==="on"}else return R==="on";return X==="ON"||
g.DI(G.videoData,"yt:cc")==="on"},yw=function(G,X){if(G.W&&(X===void 0||!X)||!G.videoData.captionTracks.length)return!1;
G=G.getAudioTrack();return!!G.N||G.W==="FORCED_ON"},b0L=function(G){var X=void 0,Q=g.BA(g.la(),65);
if(g.sB(G.tT)&&Q!=null){if($Ea(G)!=null)return!1;X=!Q}return X},Dv=function(G,X){if(!G.N)return null;
if(G.j&&G.j.V)return G.j.V;X=JNL(G,X);X=g.JE(G.N.W,X);var Q=null;if(a84(G.tT)){var R=G.U.isInline()?void 0:g.xL("yt-player-caption-sticky-language");for(var S=[R,G.videoData.captionsLanguagePreference,G.tT.captionsLanguagePreference,g.DI(G.videoData,"yt:cc_default_lang")],Z=!1,H=0;H<S.length;H++){var w=S[H];if(w){Z=!0;for(var h=0;h<X.length;h++)if(g.WM(X[h])===w)return X[h];for(h=0;h<X.length;h++)if(g.WM(X[h]).split("-")[0]===w.split("-")[0])return X[h]}}if(Z&&G.N&&(S=G.N.C,S.length))for(S=g.e(S),
Z=S.next();!Z.done;Z=S.next())if(Z=Z.value,Z.languageCode===R){Q=Z;break}}else for(R=[G.videoData.captionsLanguagePreference,G.tT.captionsLanguagePreference,g.DI(G.videoData,"yt:cc_default_lang")],S=0;S<R.length;S++)for(Z=0;Z<X.length;Z++)if(g.WM(X[Z])===R[S])return X[Z];R=null;G.j&&G.j.Y&&(R=G.j.Y);R||(R=X.find(function(L){return L.isDefault})||null);
R||(R=X[0]||f8(G));R&&Q&&g.WM(R).split("-")[0]!==Q.languageCode.split("-")[0]&&(R=EV3(R,Q));return R},f8=function(G){return G.j&&G.j.N},N_=function(G){var X=f8(G);
return!!X&&G.W===X},i03=function(G,X){var Q=G.U.EY().V0().textTracks;
G=G.W.toString();for(var R=0;R<Q.length;R++){var S=Q[R];S.id===G&&(X?S.mode!=="showing"&&(S.mode="showing"):S.mode==="showing"&&(S.mode="disabled"))}},$d=function(G,X,Q){G.loaded&&G.unload();
Q!=null&&(G.T=Q,G.T&&(g.sB(G.tT)?Ay(G,!!X):n8(G,!!X)));X!==null||yw(G,!0)||G.FA(X,!!X,G.T?"m":"s");G.W=X;yw(G)&&(G.W=f8(G));var R;GsZ(G,(R=G.W)!=null?R:void 0);G.load()},QXo=function(G,X){if(X instanceof rM){var Q=G.Yc[X.id];
Q&&Q.W!==X&&(Q.dispose(),delete G.Yc[X.id],Q=null);Q||(Q=XYG(G,X))&&(G.Yc[X.id]=Q)}else Q=X.windowId,G.wb[Q]||(G.wb[Q]=[]),G.wb[Q].push(X)},XYG=function(G,X){var Q=RjZ(G);
if(!Q)return null;var R=G.W?g.WM(G.W):null;R&&g.UqO.test(R)&&(X.params.Cv=1);var S=G.KO.getPlayerSize();R=S.height*G.yH.height;S=S.width*G.yH.width;G.tT.playerStyle!=="google-live"||G.Y.isDefault||Object.assign(X.params,G.Y);switch(X.params.Eo!=null?X.params.Eo:X.N.length>1?1:0){case 1:return new F8(X,G.Y,G.S,Q.width,Q.height,S,R,G.tT.experiments,G.DP.bind(G),G.U);case 2:return new dM(X,G.Y,G.S,Q.width,Q.height,S,R,G.tT.experiments,G.DP.bind(G),G.U);default:return new kd(X,G.Y,G.S,Q.width,Q.height,
S,R,G.tT.experiments,G.DP.bind(G),G.U)}},ANd=function(G,X,Q){Q=Q===void 0?!1:Q;
var R=bR.t1;G.Y={};Object.assign(G.Y,bR);G.Y.t1={};Object.assign(G.Y.t1,R);G.S={t1:{}};var S=X.backgroundOverride?G.S:G.Y,Z=X.background||R.background;c7.test(Z);S.t1.background=Z;S=X.colorOverride?G.S:G.Y;Z=X.color||R.color;c7.test(Z);S.t1.color=Z;S=X.windowColorOverride?G.S:G.Y;Z=X.windowColor||bR.windowColor;c7.test(Z);S.windowColor=Z;S=X.backgroundOpacityOverride?G.S:G.Y;Z=X.backgroundOpacity;Z==null&&(Z=R.backgroundOpacity);S.t1.backgroundOpacity=Z;S=X.fontSizeIncrementOverride?G.S:G.Y;Z=X.fontSizeIncrement;
Z==null&&(Z=R.fontSizeIncrement);S.t1.fontSizeIncrement=Z;Z=X.fontStyleOverride?G.S:G.Y;S=X.fontStyle;S==null&&(S=R.bold&&R.italic?3:R.bold?1:R.italic?2:0);Z=Z.t1;switch(S){case 1:Z.bold=!0;delete Z.italic;break;case 2:delete Z.bold;Z.italic=!0;break;case 3:Z.bold=!0;Z.italic=!0;break;default:delete Z.bold,delete Z.italic}S=X.textOpacityOverride?G.S:G.Y;Z=X.textOpacity;Z==null&&(Z=R.textOpacity);S.t1.textOpacity=Z;S=X.windowOpacityOverride?G.S:G.Y;Z=X.windowOpacity;Z==null&&(Z=bR.windowOpacity);S.windowOpacity=
Z;S=X.charEdgeStyleOverride?G.S:G.Y;Z=X.charEdgeStyle;Z==null&&(Z=R.charEdgeStyle);S.t1.charEdgeStyle=Z;S=X.fontFamilyOverride?G.S:G.Y;Z=X.fontFamily;Z==null&&(Z=R.fontFamily);S.t1.fontFamily=Z;G.loaded&&G.t9();Q&&g.E5("yt-player-caption-display-settings",X,2592E3)},SnH=function(G,X){if(!G.N)return{};
if(X){g.Mn(X)||G.Od(X.vss_id,"m");if(G.C||!g.Hn(X))return;if(g.Mn(X)){$d(G,null,!0);return}for(var Q,R=g.JE(G.N.W,!0),S=0;S<R.length;S++){var Z=R[S];Z.languageCode!==X.languageCode||Q&&(Z.languageName!==X.languageName||(Z.captionId||"")!==(X.captionId||"")||g.II(Z)!==X.displayName)||(Q=X.translationLanguage?EV3(Z,X.translationLanguage):Z)}G.gF(X.position);!Q||Q===G.W&&G.loaded||(X=g.s4(),R=g.WM(Q),X.length&&R===X[X.length-1]||(X.push(R),g.E5("yt-player-caption-language-preferences",X)),a84(G.tT)&&
!G.U.isInline()&&g.E5("yt-player-caption-sticky-language",R,2592E3),$d(G,Q,!0))}else return G.loaded&&G.W&&!N_(G)?g.dS(G.W):{};return""},HAa=function(G,X,Q){X&&!G.AT?(X=Pzo({Cv:0,
lang:"en"}),G.AT=[X,new K8(X.start,X.end-X.start,0,X.id,Q!=null?Q:"Captions look like this")],G.player.PZ(G.AT)):!X&&G.AT&&(ZAG(G,G.AT),G.AT=null)},ZAG=function(G,X){G.player.eN(X);
X=g.e(X);for(var Q=X.next();!Q.done;Q=X.next())g.Ev(G.QH,Q.value);wM(G.IU)},GsZ=function(G,X){G.tT.G("html5_modify_caption_vss_logging")&&(G.videoData.mS=X)},RjZ=function(G){var X=G.KO.getVideoContentRect(!0).height,Q=G.KO.getVideoContentRect(!0).width;
if(!X||!Q)return null;X*=G.yH.height;Q*=G.yH.width;return{width:Q,height:X}},n8=function(G,X){if(G.storage)try{G.storage.set("module-enabled",X)}catch(Q){}},Ay=function(G,X){G.U.isInline()||g.E5("yt-player-sticky-caption",X,2592E3)},$Ea=function(G){if(!G.U.isInline())return g.xL("yt-player-sticky-caption")},Ne4=function(G){var X,Q=!((X=G.U.EY())==null||!X.DB());
return G.Xm&&Q&&G.V!=="LIVE"&&G.V!=="SABR_LIVE"},JNL=function(G,X){g.SA(G.videoData)&&(X=!0);
X||(X=G.V==="TTS"?!1:G.V==="INNERTUBE"?!1:!0);return X||G.tT.G("web_deprecate_always_includes_asr_setting")&&g.sB(G.tT)?!0:!!g.BA(g.la(),66)};
g.TK.prototype.Vr=g.Sy(71,function(){return!1});
g.TK.prototype.Xc=g.Sy(70,function(){});
g.Kb.prototype.Xc=g.Sy(69,function(G,X,Q){var R=this;this.U_();X=this.v_(G,X);var S=this.PM.Z().G("html5_report_captions_ctmp_qoe"),Z=(0,g.TB)();this.uD();ePS(this,X,{format:"RAW",onSuccess:function(H){R.N=null;if(S){var w=(H.responseText.length/1024).toFixed(),h=(0,g.TB)();R.videoData.Ni("capresp",{ms:h-Z,kb:w})}Q.h0(H.responseText,G)},
onError:S?function(H){var w;H=(w=H==null?void 0:H.status)!=null?w:0;R.videoData.Ni("capfail",{status:H})}:void 0,
withCredentials:!0})});
g.rQ.prototype.Xc=g.Sy(68,function(G,X,Q){var R=this;this.U_();X=this.v_(G,X);this.uD();this.N=g.PT(X,{format:"RAW",onSuccess:function(S){R.N=null;Q.h0(S.responseText,G)},
withCredentials:!0})});
g.yS.prototype.zz=g.Sy(67,function(){for(var G=g.wy(document,"track",void 0,this.N),X=0;X<G.length;X++)g.Tt(G[X])});
g.CI.prototype.zz=g.Sy(66,function(){this.mediaElement.zz()});
g.yS.prototype.RH=g.Sy(65,function(){return!(!this.N.textTracks||!this.N.textTracks.addEventListener)});
g.CI.prototype.RH=g.Sy(64,function(){return this.mediaElement.RH()});
g.yS.prototype.DB=g.Sy(63,function(){return!!this.N.textTracks});
g.CI.prototype.DB=g.Sy(62,function(){return this.mediaElement.DB()});
g.yS.prototype.R2=g.Sy(61,function(G){for(var X=0;X<G.length;X++)this.N.appendChild(G[X])});
g.CI.prototype.R2=g.Sy(60,function(G){this.mediaElement.R2(G)});
g.Ri.prototype.Zt=g.Sy(59,function(G,X,Q){this.UY.Zt(G,X,Q)});
g.$b.prototype.Zt=g.Sy(58,function(G,X,Q){this.W.set(G,{zC:X,jt:Q})});
g.br.prototype.Zt=g.Sy(57,function(G,X,Q){this.yH.Zt(G,X,Q)});
g.Ri.prototype.Mp=g.Sy(56,function(G){return this.UY.Mp(G)});
g.br.prototype.Mp=g.Sy(55,function(G){var X=2;this.C.has(G)?X=0:g.MBC(this,G)&&(X=1);return X});
g.WP.prototype.XS=g.Sy(43,function(G){var X=this.app.a6({playerType:void 0});return X?X.XS(G):!1});
g.XK.prototype.XS=g.Sy(42,function(G){return this.uB.dL.XS(G)});
g.zc.prototype.XS=g.Sy(41,function(G){return this.Gj().some(function(X){return X.namespace===G})});
g.Ww.prototype.XS=g.Sy(40,function(){return!1});
g.WP.prototype.Od=g.Sy(38,function(G,X){this.app.eA().Od(G,X)});
g.XK.prototype.Od=g.Sy(37,function(G,X){this.uB.Od(G,X)});
g.$K.prototype.Od=g.Sy(36,function(G,X){G=[G,X];g.nY(this,g.vd(this.provider),"cfi",G)});
g.xc.prototype.Od=g.Sy(35,function(G,X){this.qoe&&this.qoe.Od(G,X)});
g.iO.prototype.Od=g.Sy(34,function(G,X){this.Q0.Od(G,X)});
g.Ww.prototype.Od=g.Sy(33,function(){});
g.WP.prototype.FA=g.Sy(32,function(G,X,Q){this.app.eA().FA(G,X,Q)});
g.XK.prototype.FA=g.Sy(31,function(G,X,Q){this.uB.FA(G,X,Q)});
g.$K.prototype.FA=g.Sy(30,function(G,X,Q){if(this.IU!==G||this.Js!==X)X=X==="rawcc"?"":X,Q=[G,X,this.IU,Q],g.nY(this,g.vd(this.provider),"cfs",Q),this.IU=G,this.Js=X});
g.xc.prototype.FA=g.Sy(29,function(G,X,Q){this.qoe&&this.qoe.FA(G,X,Q)});
g.iO.prototype.FA=g.Sy(28,function(G,X,Q){this.Q0.FA(G,X,Q)});
g.Ww.prototype.FA=g.Sy(27,function(){});
g.QE.prototype.PQ=g.Sy(12,function(){return this.T});
g.Y9.prototype.PQ=g.Sy(11,function(){return this.eA().ST()});
g.WP.prototype.ST=g.Sy(10,function(){return this.app.PQ()});
g.XK.prototype.ST=g.Sy(9,function(){return this.uB.ST()});
g.iO.prototype.ST=g.Sy(8,function(){var G;return((G=this.loader)==null?void 0:G.PQ())||null});
g.Ww.prototype.ST=g.Sy(7,function(){return null});
g.iF.prototype.oa=g.Sy(1,function(G){return(G=this.DO(G))?G.N:0});
g.zu.prototype.oa=g.Sy(0,function(){return 0});
var c3G=/#(.)(.)(.)/,zPZ=/^#(?:[0-9a-f]{3}){1,2}$/i,Voo={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};hy.prototype.contains=function(G){G=g.fa(this.segments,G);return G>=0||G<0&&(-G-1)%2===1};
hy.prototype.length=function(){return this.segments.length/2};
g.T(FHv,g.I);g.P=FHv.prototype;g.P.zT=function(){g.I.prototype.zT.call(this);this.Y&&this.Y.cancel()};
g.P.jM=function(){this.seekTo(this.player.getCurrentTime())};
g.P.seekTo=function(G){G-=this.player.q9();var X=this.N;this.N=g.uL(this.AT.Q3(G).LO);X!==this.N&&this.j&&this.j()};
g.P.reset=function(){this.V=new hy;this.S=-1;this.Y&&(this.Y.cancel(),this.Y=null)};
g.P.nB=function(){this.U_();var G;if(G=this.N!=null)G=this.N,G=G.N.BX(G);if(G&&!this.Y&&!(this.N&&this.N.startTime-this.player.getCurrentTime()>30)){G=this.N;G=G.N.O0(G);var X=G.LO[0],Q;if((Q=this.player.getVideoData())==null?0:Q.enableServerStitchedDai)if(Q=this.player.ST()){var R=X.N.info.id,S=X.oU,Z=G.LO[0].C;if(this.policy.QH){if(Q=Q.Qs(Z,S,R,3))G.V=Q}else if(R=Q.J3(Z,S,R,3))if(Q=Q.Mp(S),Q===0)R&&(G.N=new g.D1(R));else if(Q===2){this.J.start();CZG(this)&&this.seekTo(this.player.getCurrentTime());
return}}X.N.index.PD(X.oU)?(this.V.contains(G.LO[0].oU)||ton(this,G),this.N=g.uL(G.LO)):CZG(this)&&this.seekTo(this.player.getCurrentTime())}this.J.start()};
g.T(L8,g.TK);g.P=L8.prototype;g.P.Xc=function(G,X,Q){var R=this;this.uD();X=dmG(this,G.getId());X||(X=G.languageCode,X=this.N.isManifestless?WHo(this,X,"386"):WHo(this,X));if(X){var S=(X.index.oa(X.index.Uu())-X.index.getStartTime(X.index.Uu()))*1E3,Z=new g.fCC(this.U.Z());this.V=new FHv(Z,this.U,X,function(H,w){Q.h0(H,G,w,S)},this.J||g.AR(X.info),function(){R.V&&R.V.reset();
R.S=!0})}};
g.P.Vr=function(){var G=this.S;this.S=!1;return G};
g.P.zG=function(G){var X=this.U.Z().G("html5_fallback_if_rawcc_missing");var Q=this.N.N.rawcc!=null;if(!this.J||!Q&&X)X=this.N.isManifestless?I8H(this,"386"):I8H(this);else{if(!Q){this.logger.N(386248249,"rawcc used but unavailable");return}X=[new g.VT({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.VT({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}X=g.e(X);
for(Q=X.next();!Q.done;Q=X.next())g.sS(this.W,Q.value);G.lF()};
g.P.uD=function(){this.V&&(this.V.dispose(),this.V=null)};
g.P.v_=function(){return""};
var c7=/^#(?:[0-9a-f]{3}){1,2}$/i;var f8d=["left","right","center","justify"];g.T(kd,g.f);g.P=kd.prototype;g.P.ew=function(G,X){this.Xm=G;this.cM=X;var Q=g.GX(this.element,this.element.parentElement);this.BM=G-Q.x;this.KO=X-Q.y};
g.P.cj=function(G,X){if(G!==this.Xm||X!==this.cM){g.iv(this.element,"ytp-dragging")||g.Gk(this.element,"ytp-dragging");var Q=g.Qj(this.element);G=G-this.BM-.02*this.R6;var R=X-this.KO-.02*this.f7,S=(G+Q.width/2)/this.maxWidth*3;S=Math.floor(g.pT(S,0,2));var Z=(R+Q.height/2)/this.maxHeight*3;Z=Math.floor(g.pT(Z,0,2));X=S+Z*3;G=(G+S/2*Q.width)/this.maxWidth;G=g.pT(G,0,1)*100;Q=(R+Z/2*Q.height)/this.maxHeight;Q=g.pT(Q,0,1)*100;this.W.params.rV=X;this.W.params.dK=Q;this.W.params.D1=G;this.W.params.isDefault=
!1;this.N.rV=X;this.N.dK=Q;this.N.D1=G;this.N.isDefault=!1;this.yH.rV=X;this.yH.dK=Q;this.yH.D1=G;this.yH.isDefault=!1;this.FK()}};
g.P.Jl=function(){g.QD(this.element,"ytp-dragging")};
g.P.FK=function(){this.e6(this.J)};
g.P.e6=function(G){var X=this.bB?0:Math.min(this.Xx(),this.maxWidth),Q=this.wW(),R=this.bB;if(R){var S=getComputedStyle(this.V.parentNode);S=Yd(S.borderLeftWidth)+Yd(S.borderRightWidth)+Yd(S.paddingLeft)+Yd(S.paddingRight)}else S=0;var Z=S;S="";this.W.params.Cv===3&&(S="rotate(180deg)");var H=R?"calc(96% - "+Z+"px)":"96%";g.DN(this.element,{top:0,left:0,right:"",bottom:"",width:X?X+"px":"",height:Q?Q+"px":"","max-width":H,"max-height":H,margin:"",transform:""});this.MD(G);S={transform:S,top:"",left:"",
width:X?X+"px":"",height:Q?Q+"px":"","max-width":"","max-height":""};var w=this.N.D1*.96+2;H=this.N.rV;switch(H){case 0:case 3:case 6:(R=this.N.t1.fontSizeIncrement)&&R>0&&this.N.Cv!==2&&this.N.Cv!==3&&(w=Math.max(w/(1+R*2),2));S.left=w+"%";break;case 1:case 4:case 7:S.left=w+"%";w=this.V.offsetWidth;X||w?(X=X||w+1,S.width=X+"px",S["margin-left"]=R?X/-2-Z/2+"px":X/-2+"px"):S.transform+=" translateX(-50%)";break;case 2:case 5:case 8:S.right=100-w+"%"}R=this.N.dK*.96+2;switch(H){case 0:case 1:case 2:S.top=
R+"%";break;case 3:case 4:case 5:S.top=R+"%";(Q=Q||this.element.clientHeight)?(S.height=Q+"px",S["margin-top"]=Q/-2+"px"):S.transform+=" translateY(-50%)";break;case 6:case 7:case 8:S.bottom=100-R+"%"}g.DN(this.element,S);if(this.S){Q=this.V.offsetHeight;R=1;for(X=0;X<G.length;X++)S=G[X],typeof S.text==="string"&&(R+=S.text.split("\n").length-1,S.append||X===0||R++);Q/=R;this.S.style.height=Q+"px";this.S.style.width=Q+"px";this.element.style.paddingLeft=Q+5+"px";this.element.style.paddingRight=Q+
5+"px";G=Number(this.element.style.marginLeft.replace("px",""))-Q-5;Q=Number(this.element.style.marginRight.replace("px",""))-Q-5;this.element.style.marginLeft=G+"px";this.element.style.marginRight=Q+"px"}};
g.P.MD=function(G){var X;for(X=0;X<G.length&&G[X]===this.J[X];X++);if(this.Mi||this.J.length>X)X=0,this.Mi=!1,this.J=[],this.T=this.IU=this.QH=null,g.Pq(this.V);for(;X<G.length;X++)$mV(this,G[X])};
g.P.Xx=function(){return 0};
g.P.wW=function(){return 0};
g.P.toString=function(){return g.f.prototype.toString.call(this)};vV4.prototype.clear=function(){this.Y=this.time=this.mode=0;this.N=[];this.reset()};
vV4.prototype.reset=function(){this.mode=0;this.V.reset(0);this.C.reset(1)};
var J3O=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];jH.prototype.set=function(G){this.type=G};
jH.prototype.get=function(){return this.type};
M_.prototype.clear=function(){this.state=0};
M_.prototype.update=function(){this.state=this.state===2?1:0};
M_.prototype.eG=function(){return this.state!==0};
M_.prototype.matches=function(G,X){return this.eG()&&G===this.EL&&X===this.gk};
R0S.prototype.reset=function(){this.timestamp=this.N=0};
m1.prototype.updateTime=function(G){for(var X=1;X<=15;++X)for(var Q=1;Q<=32;++Q)this.Y[X][Q].timestamp=G};
m1.prototype.debugString=function(){for(var G="\n",X=1;X<=15;++X){for(var Q=1;Q<=32;++Q){var R=this.Y[X][Q];G=R.N===0?G+"_":G+String.fromCharCode(R.N)}G+="\n"}return G};
m1.prototype.reset=function(G){for(var X=0;X<=15;X++)for(var Q=0;Q<=32;Q++)this.Y[X][Q].reset();this.V=G;this.N=0;this.W=this.row=1};
var SxS=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Z0v=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],H0O=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],qxG=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];k2v.prototype.reset=function(G,X){this.C=X;this.style.set(2);this.W=this.S;this.V=this.J;this.N=this.W;var Q=(G<<2)+(X<<1);this.S.reset(Q);this.J.reset(Q);this.text.reset((G<<2)+(X<<1)+1)};
bOd.prototype.reset=function(G){this.C=G;this.W.clear();this.V=this.Y;this.Y.reset(G,0);this.S.reset(G,1)};mEv.prototype.V=function(){};g.T(K8,g.yG);K8.prototype.toString=function(){return g.yG.prototype.toString.call(this)};g.T(eH,g.I);eH.prototype.reset=function(){};g.T(rM,g.yG);rM.prototype.toString=function(){return g.yG.prototype.toString.call(this)};
var a4=0;g.T(Es,eH);Es.prototype.reset=function(){this.J={};this.W=this.N=null;this.S=!0};
Es.prototype.Y=function(G,X){G=G.firstChild;G.getAttribute("format");X=X||0;Number.isFinite(X);G=Array.from(G.childNodes);G=g.e(G);for(var Q=G.next();!Q.done;Q=G.next())if(Q=Q.value,Q.nodeType===1)switch(Q.tagName){case "head":var R=Q;break;case "body":var S=Q}if(R)for(R=Array.from(R.childNodes),R=g.e(R),G=R.next();!G.done;G=R.next())if(G=G.value,G.nodeType===1)switch(G.tagName){case "pen":Q=G.getAttribute("id");var Z=this.pens,H={},w=G.getAttribute("p");w&&Object.assign(H,this.pens[w]);w=Os(G,"b");
w!=null&&(H.bold=w);w=Os(G,"i");w!=null&&(H.italic=w);w=Os(G,"u");w!=null&&(H.underline=w);w=zF(G,"et");w!=null&&(H.charEdgeStyle=w);w=zF(G,"of");w!=null&&(H.offset=w);w=gM(G,"bc");w!=null&&(H.background=w);w=gM(G,"ec");w!=null&&(H.kd=w);w=gM(G,"fc");w!=null&&(H.color=w);w=zF(G,"fs");w!=null&&w!==0&&(H.fontFamily=w);w=xd(G,"sz");w!==void 0&&(H.fontSizeIncrement=w/100-1);w=xd(G,"bo");w!==void 0&&(H.backgroundOpacity=w/255);w=xd(G,"fo");w!==void 0&&(H.textOpacity=w/255);w=zF(G,"rb");w!=null&&w!==10&&
w!==0&&(H.VG=w>10?w-1:w);G=zF(G,"hg");G!=null&&(H.eF=G);Z[Q]=H;break;case "ws":Q=G.getAttribute("id");this.j[Q]=snd(this,G);break;case "wp":Q=G.getAttribute("id"),this.T[Q]=Te3(this,G)}if(S){R=[];S=Array.from(S.childNodes);S=g.e(S);for(G=S.next();!G.done;G=S.next())if(G=G.value,G.nodeType===1)switch(G.tagName){case "w":this.N=KNa(this,G,X,!1);(G=this.J[this.N.id])&&G.end>this.N.start&&(G.end=this.N.start);this.J[this.N.id]=this.N;R.push(this.N);break;case "p":var h=G;w=X;Q=[];Z=h.getAttribute("w")||
this.C;H=!!Os(h,"a");w=(xd(h,"t")||0)+w;var L=xd(h,"d")||5E3;H||(!this.S&&this.W&&this.W.windowId===Z&&this.W.end>w&&(this.W.end=w),this.W&&this.W.text==="\n"&&(this.W.text=""));var k=H?6:5,Y=h.getAttribute("p");Y=Y?this.pens[Y]:null;var M=Array.from(h.childNodes);M.length&&(this.S=h.getAttribute("d")!=null);for(h=0;h<M.length;h++){var m=M[h],u=void 0;h>0&&(H=!0);var r=void 0;m.nodeType===1&&(r=m);if(r&&r.tagName==="s"){if((m=(m=r.getAttribute("p"))?this.pens[m]:null)&&m.VG&&(m.VG===1?(m=M.slice(h,
h+4),m.length===4&&(u=ubO(w,L,Z,H,k,m,this.pens),h+=3)):u=ubO(w,L,Z,H,k,[r],this.pens)),!u){var x=r;u=w;r=L;m=Z;var c=H,z=k,B=x.textContent?x.textContent:"",V=x.getAttribute("p");V=V?this.pens[V]:null;x=xd(x,"t")||0;u=new K8(u+x,r-x,z,m,B,c,V)}}else u=new K8(w,L,k,Z,m.textContent||"",H,Y);Q.push(u);this.W=u}if(Q.length>0)for(Q[0].windowId===this.C&&(this.N=KNa(this,G,X,!0),R.push(this.N)),G=g.e(Q),Q=G.next();!Q.done;Q=G.next())Q=Q.value,Q.windowId=this.N.id,this.N.N.push(Q),R.push(Q)}X=R}else X=[];
return X};var qnO=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.T(Us,eH);Us.prototype.reset=function(){this.W.clear()};
Us.prototype.Y=function(G,X){var Q=JSON.parse(G);if(!Q)return[];if(Q.pens){G=0;for(var R=g.e(Q.pens),S=R.next();!S.done;S=R.next()){S=S.value;var Z={},H=S.pParentId;H&&Object.assign(Z,this.N.get(H));S.bAttr&&(Z.bold=!0);S.iAttr&&(Z.italic=!0);S.uAttr&&(Z.underline=!0);H=S.ofOffset;H!=null&&(Z.offset=H);S.szPenSize!==void 0&&(Z.fontSizeIncrement=S.szPenSize/100-1);H=S.etEdgeType;H!=null&&(Z.charEdgeStyle=H);S.ecEdgeColor!==void 0&&(Z.kd=lR(S.ecEdgeColor));H=S.fsFontStyle;H!=null&&H!==0&&(Z.fontFamily=
H);S.fcForeColor!==void 0&&(Z.color=lR(S.fcForeColor));S.foForeAlpha!==void 0&&(Z.textOpacity=S.foForeAlpha/255);S.bcBackColor!==void 0&&(Z.background=lR(S.bcBackColor));S.boBackAlpha!==void 0&&(Z.backgroundOpacity=S.boBackAlpha/255);(H=S.rbRuby)&&H!==10&&(Z.VG=H>10?H-1:H,Z.textEmphasis=qnO.get(Z.VG));S.hgHorizGroup&&(Z.eF=S.hgHorizGroup);this.N.set(G++,Z)}}if(Q.wsWinStyles)for(G=0,R=g.e(Q.wsWinStyles),S=R.next();!S.done;S=R.next())S=S.value,Z={},(H=S.wsParentId)?Object.assign(Z,this.C.get(H)):Object.assign(Z,
this.S),S.mhModeHint!==void 0&&(Z.Eo=S.mhModeHint),S.juJustifCode!==void 0&&(Z.textAlign=S.juJustifCode),S.pdPrintDir!==void 0&&(Z.Cv=S.pdPrintDir),S.sdScrollDir!==void 0&&(Z.Og=S.sdScrollDir),S.wfcWinFillColor!==void 0&&(Z.windowColor=lR(S.wfcWinFillColor)),S.wfoWinFillAlpha!==void 0&&(Z.windowOpacity=S.wfoWinFillAlpha/255),this.C.set(G++,Z);if(Q.wpWinPositions)for(G=0,R=g.e(Q.wpWinPositions),S=R.next();!S.done;S=R.next())S=S.value,Z={},(H=S.wpParentId)&&Object.assign(Z,this.V.get(H)),S.ahHorPos!==
void 0&&(Z.D1=S.ahHorPos),S.apPoint!==void 0&&(Z.rV=S.apPoint),S.avVerPos!==void 0&&(Z.dK=S.avVerPos),S.ccCols!==void 0&&(Z.AD=S.ccCols),S.rcRows!==void 0&&(Z.D8=S.rcRows),this.V.set(G++,Z);if(Q.events){G=[];Q=g.e(Q.events);for(R=Q.next();!R.done;R=Q.next()){var w=R.value;S=(w.tStartMs||0)+X;Z=w.dDurationMs||0;if(w.id)H=String(w.id),R=e0d(this,w,S,Z,H),G.push(R),this.W.set(H,R);else{w.wWinId?H=w.wWinId.toString():(H="_"+a4++,R=e0d(this,w,S,Z,H),G.push(R),this.W.set(H,R));R=G;var h=w;Z===0&&(Z=5E3);
w=this.W.get(H);var L=!!h.aAppend,k=L?6:5,Y=h.segs,M=null;h.pPenId&&(M=this.N.get(h.pPenId));for(h=0;h<Y.length;h++){var m=Y[h],u=m.utf8;if(u){var r=m.tOffsetMs||0,x=null;m.pPenId&&(x=this.N.get(m.pPenId));if((w.params.Eo!=null?w.params.Eo:w.N.length>1?1:0)===2&&L&&u==="\n")continue;m=null;var c=[],z;if(z=x&&x.VG===1){z=Y;var B=h;if(B+3>=z.length||!z[B+1].pPenId||!z[B+2].pPenId||!z[B+3].pPenId)z=!1;else{var V=z[B+1].pPenId;(V=this.N.get(V))&&V.VG&&V.VG===2?(V=z[B+2].pPenId,V=this.N.get(V),!V||!V.VG||
V.VG<3?z=!1:(V=z[B+3].pPenId,z=(V=this.N.get(V))&&V.VG&&V.VG===2?!0:!1)):z=!1}}if(z)r=Y[h+1].utf8,m=Y[h+3].utf8,z=Y[h+2].utf8,B=this.N.get(Y[h+2].pPenId),u=oaa(u,r,z,m,B),m=new K8(S,Z,k,H,u,L,x),h+=3;else{if(u.indexOf("<")>-1){var p=void 0;c=x;z=M;B=S;V=Z;var b=r,A=k,wX=L,qe=[],hG=g.NR("<html>"+u+"</html>");if(!hG.getElementsByTagName("parsererror").length&&((p=hG.firstChild)==null?0:p.childNodes.length))for(p=g.e(hG.firstChild.childNodes),hG=p.next();!hG.done;hG=p.next()){hG=hG.value;var jy=void 0,
QZ=void 0,gX=(QZ=(jy=hG.textContent)==null?void 0:jy.replace(/\n/g,""))!=null?QZ:"";if(hG.nodeType!==3||gX&&gX.match(/^ *$/)==null){jy={};Object.assign(jy,c||z);QZ=void 0;switch((QZ=hG)==null?void 0:QZ.tagName){case "b":jy.bold=!0;break;case "i":jy.italic=!0;break;case "u":jy.underline=!0}qe.push(new K8(B+b,V-b,A,w.id,gX,wX,jy))}}c=qe}c.length||(c=[new K8(S+r,Z-r,k,w.id,u,L,x||M)])}if(c.length)for(L=g.e(c),x=L.next();!x.done;x=L.next())x=x.value,R.push(x),w.N.push(x);else m&&(R.push(m),w.N.push(m))}L=
!0}}}X=G}else X=[];return X};g.T(B7,g.TK);B7.prototype.Xc=function(G,X,Q){OOa(this.videoData.videoId,G.vssId,Q.h0)};
B7.prototype.zG=function(G){if(this.audioTrack)for(var X=g.e(this.audioTrack.captionTracks),Q=X.next();!Q.done;Q=X.next())g.sS(this.W,Q.value);G.lF()};g.T(F8,kd);F8.prototype.MD=function(G){var X=this.W.N;kd.prototype.MD.call(this,G);for(G=G.length;G<X.length;G++){var Q=X[G];if(Z&&Q.N===S)var R=Z;else{R={};Object.assign(R,Q.N);Object.assign(R,wYn);var S=Q.N;var Z=R}$mV(this,Q,R)}};
var wYn={D0:!0};g.T(C8,mEv);C8.prototype.V=function(G,X,Q,R,S){if(Q<R){var Z="_"+a4++;Q=Q/1E3-this.S;R=R/1E3-this.S;G=new rM(Q,R-Q,5,Z,{textAlign:0,rV:0,D1:X*2.5,dK:G*5.33});S=new K8(Q,R-Q,5,Z,S);this.W.push(G);this.W.push(S)}};
g.T(I4,eH);I4.prototype.Y=function(G){G=new C8(G,G.byteLength,this.W);if(rNL(G)){for(;G.byteOffset<G.N.byteLength;)for(G.version===0?G.Y=Vw(G)*(1E3/45):G.version===1&&(G.Y=Vw(G)*4294967296+Vw(G)),G.C=ty(G);G.C>0;G.C--){var X=ty(G),Q=ty(G),R=ty(G);X&4&&(X&3)===this.track&&(this.track===0||this.track===1)&&(X=this.N,X.N.push({time:G.Y,type:this.track,aT:Q,IT:R,order:X.N.length}))}QnG(this.N,G);return G.W}return[]};
I4.prototype.reset=function(){this.N.clear()};g.T(dM,kd);g.P=dM.prototype;g.P.FK=function(){g.NO(this.N9)};
g.P.w4=function(){this.element.removeEventListener("transitionend",this.w4,!1);g.QD(this.element,"ytp-rollup-mode");this.e6(this.C7,!0)};
g.P.wW=function(){return this.Y?this.AT:this.j};
g.P.Xx=function(){return this.Y?this.j:this.AT};
g.P.e6=function(G,X){this.C7=G;if(this.W.params.D8){for(var Q=0,R=0;R<this.J.length&&Q<G.length;R++)this.J[R]===G[Q]&&Q++;Q>0&&Q<G.length&&(G=this.J.concat(G.slice(Q)));this.As=this.AT;this.j=this.AT=0;kd.prototype.e6.call(this,G);O0O(this,X)}kd.prototype.e6.call(this,G)};z0S.prototype.unload=function(){this.N!=null&&(this.U.removeEventListener("sabrCaptionsDataLoaded",this.N),this.N=null);this.u9=[];this.U.publish("sabrCaptionsBufferedRangesUpdated",this.u9)};
z0S.prototype.nJ=function(G){return{formatId:g.bn(G.info.N.info,this.IW),oU:G.info.oU+(this.IW?0:1),startTimeMs:G.info.C*1E3,durationMs:G.info.T*1E3}};g.T(W7,g.TK);W7.prototype.Xc=function(G,X,Q){this.uD();X=G.getId();X=X!=null&&X in this.N.N?this.N.N[X]:null;X||(X=G.languageCode,X=this.N.isManifestless?Beo(this,X,"386"):Beo(this,X));X&&(this.V=G,this.S=X,UEv(this.J,Q),this.U.publish("sabrCaptionsTrackChanged",g.bn(X.info,this.N.IW)))};
W7.prototype.zG=function(G){var X=this.N.isManifestless?lWa(this,"386"):lWa(this);X=g.e(X);for(var Q=X.next();!Q.done;Q=X.next())g.sS(this.W,Q.value);G.lF()};
W7.prototype.uD=function(){this.V&&(this.V=this.S=null,this.J.unload(),this.U.publish("sabrCaptionsTrackChanged",null))};
W7.prototype.v_=function(){return""};var t5S="WEBVTT".split("").map(function(G){return G.charCodeAt(0)});
g.T(Czn,eH);
Czn.prototype.Y=function(G,X){G instanceof ArrayBuffer&&(G=g.jx(new Uint8Array(G)));var Q=[];G=G.split(hja);for(var R=1;R<G.length;R++){var S=G[R],Z=X;if(S!==""&&!Ltv.test(S)){var H=ksS.exec(S);if(H&&H.length>=4){var w=dE4(H[1]),h=dE4(H[2])-w;w+=Z;var L=(H=H[3])?H.split(" "):[];H={};var k=null;var Y="";var M=null,m="";L=g.e(L);for(var u=L.next();!u.done;u=L.next())if(u=u.value.split(":"),u.length===2){var r=u[1];switch(u[0]){case "line":u=r.split(",");u[0].endsWith("%")&&(k=u[0],H.dK=Number.parseInt(k,
10),u.length===2&&(Y=u[1].trim()));break;case "position":u=r.split(",");M=u[0];H.D1=Number.parseInt(M,10);u.length===2&&(m=u[1].trim());break;case "align":switch(r){case "start":H.textAlign=0;break;case "middle":H.textAlign=2;break;case "end":H.textAlign=1}}}k||Y||(Y="end");if(!M)switch(H.textAlign){case 0:H.D1=0;break;case 1:H.D1=100;break;case 2:H.D1=50}if(H.textAlign!=null){k=0;switch(Y){case "center":k+=3;break;case "end":k+=6;break;default:k+=0}switch(m){case "line-left":k+=0;break;case "center":k+=
1;break;case "line-right":k+=2;break;default:switch(H.textAlign){case 0:k+=0;break;case 2:k+=1;break;case 1:k+=2}}Y=k<0||k>8?7:k;H.rV=Y}S=S.substring(ksS.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");m=H;H=S;S={};if(H.indexOf("<")<0&&H.indexOf("&")<0)Z=WNZ(w,h,5,m),h=new K8(w,h,5,Z.id,H,!1,g.Mn(S)?void 0:S),Q.push(Z),Q.push(h),Z.N.push(h);else for(Y=H.split(Ynk),Y.length===1?(H=5,m=WNZ(w,h,H,m)):(k=H=6,m=Object.assign({AD:32},m),m=new rM(w,h,k,"_"+a4++,m)),Q.push(m),k=w,M=0;M<Y.length;M++)L=Y[M],
M%2===0?(u=g.NR("<html>"+L+"</html>"),u.getElementsByTagName("parsererror").length?(r=u.createElement("span"),r.appendChild(u.createTextNode(L))):r=u.firstChild,IWV(this,k,h-(k-w),H,m,M>0,r,S,Q)):k=dE4(L)+Z}ksS.lastIndex=0}}return Q};
var Ltv=/^NOTE/,hja=/(?:\r\n|\r|\n){2,}/,ksS=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Ynk=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.T(p8,g.I);p8.prototype.clear=function(){this.N&&this.N.dispose();this.N=null};
p8.prototype.reset=function(){this.N&&this.N.reset()};
p8.prototype.zT=function(){g.I.prototype.zT.call(this);this.clear()};var bR={windowColor:"#080808",windowOpacity:0,textAlign:2,rV:7,D1:50,dK:100,isDefault:!0,t1:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.T(naH,g.P6);g.P=naH.prototype;g.P.zT=function(){if(this.C||this.DC){var G=this.U.EY();G&&!G.U_()&&G.zz()}else HAa(this,!1);g.P6.prototype.zT.call(this)};
g.P.Mt=function(){return this.tT.G("html5_honor_caption_availabilities_in_audio_track")&&this.V!=="LIVE"&&this.V!=="SABR_LIVE"};
g.P.Jw=function(){if(this.Xm)return this.C||this.DC;var G=this.getAudioTrack();if(this.Mt()){if(!G.captionTracks.length)return!1;if(!this.N)return!0}G=r3n(G,g.sB(this.tT));return G==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:G==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?yw(this):b0L(this)||yw(this)?!0:va4(this)};
g.P.load=function(){g.P6.prototype.load.call(this);this.j=this.getAudioTrack();if(this.N)this.W&&(this.cM.clear(),this.C?i03(this,!0):this.player.getPresentingPlayerType()!==3&&this.N.Xc(this.W,"json3",this.N9),this.C||this.DC||N_(this)||this.player.tS("captionschanged",g.dS(this.W)));else{var G;this.V==="OFFLINE"?G=new B7(this.player,this.videoData,this.getAudioTrack()):this.V==="SABR_LIVE"?G=new W7(this.videoData.N,this.player):this.V==="LIVE"?G=new L8(this.videoData.N,this.player):this.V==="INNERTUBE"?
G=new g.Kb(this.player,this.videoData,this.getAudioTrack()):G=new g.rQ(this.player,this.videoData.Mj,this.videoData.videoId,g.$hS(this.videoData),this.videoData.Zg,this.videoData.eventId);this.N=G;g.d(this,this.N);this.N.zG(this.N9)}};
g.P.unload=function(){this.C&&this.W?i03(this,!1):(this.SA&&g.Ax(this.SA),this.player.lf("captions"),this.QH=[],this.N&&this.N.uD(),this.cM.clear(),this.AT&&this.player.PZ(this.AT),this.t9());g.P6.prototype.unload.call(this);this.player.Ja();this.player.tS("captionschanged",{})};
g.P.create=function(){this.Jw()&&this.load();var G;a:{var X,Q,R;if(this.tT.G("web_player_nitrate_promo_tooltip")&&((X=this.videoData.getPlayerResponse())==null?0:(Q=X.captions)==null?0:(R=Q.playerCaptionsTracklistRenderer)==null?0:R.enableTouchCaptionsNitrate)){var S,Z;if(X=(G=this.videoData.getPlayerResponse())==null?void 0:(S=G.captions)==null?void 0:(Z=S.playerCaptionsTracklistRenderer)==null?void 0:Z.captionTracks)for(G=g.e(X),S=G.next();!S.done;S=G.next())if(S=S.value,S.kind==="asr"&&S.languageCode===
"en"){G=!0;break a}}G=!1}G&&this.U.publish("showpromotooltip",this.J.element)};
g.P.lF=function(){var G=r3n(this.player.getAudioTrack(),g.sB(this.tT));var X=G==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?Dv(this,this.T):G==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&yw(this)?f8(this):b0L(this)||this.T||va4(this)?Dv(this,this.T):yw(this)?f8(this):null;if(this.C||this.DC){var Q=g.JE(this.N.W,!0);G=[];for(var R=0;R<Q.length;R++){var S=Q[R],Z=g.ml("TRACK");Z.setAttribute("kind","subtitles");Z.setAttribute("label",g.II(S));Z.setAttribute("srclang",g.WM(S));Z.setAttribute("id",S.toString());
this.DC||Z.setAttribute("src",this.N.v_(S,"vtt"));S===X&&Z.setAttribute("default","1");G.push(Z)}X=this.U.EY();X.R2(G);G=X.V0();this.bB&&this.Mi.B(G.textTracks,"change",this.CfC)}else!this.W&&X&&$d(this,X),this.player.tS("onCaptionsTrackListChanged"),this.player.vR("onApiChange")};
g.P.CfC=function(){for(var G=this.U.EY().V0().textTracks,X=null,Q=0;Q<G.length;Q++)if(G[Q].mode==="showing")a:{X=g.JE(this.N.W,!0);for(var R=0;R<X.length;R++)if(X[R].toString()===G[Q].id){X=X[R];break a}X=null}(this.loaded?this.W:null)!==X&&$d(this,X,!0)};
g.P.AoO=function(){!this.W&&this.C||this.unload()};
g.P.h0=function(G,X,Q,R){if(G){var S;GsZ(this,(S=this.W)!=null?S:void 0);this.N.Vr()&&(this.QH=[],this.U.lf("captions"),wM(this.IU),this.cM.reset());a:{S=this.cM;R=R||0;Q=yNZ(S,G,Q||0);G=[];try{for(var Z=g.e(Q),H=Z.next();!H.done;H=Z.next()){var w=H.value,h=w.trackData,L=w.ir,k=S.tT.G("safari_live_drm_captions_fix");if(typeof h!=="string"){Q=G;var Y=Q.concat;if(k&&V5G(h))var M=fWk(S,h,L);else{var m=S,u=X,r=h,x=L,c=R;if(!aWH(r))throw Error("Invalid binary caption track data");m.N||(m.N=new I4(c,u));
M=m.N.Y(r,x)}var z=Y.call(Q,M)}else{if(h.substring(0,6)==="WEBVTT")var B=G.concat(fWk(S,h,L));else{Q=G;var V=Q.concat;b:{u=m=void 0;r=S;x=X;if(h[0]==="{")try{r.N||(r.N=new Us(DEL(x)));var p=u=r.N.Y(h,L);break b}catch(QZ){g.aU(QZ);p=[];break b}var b=g.NR(h);if(!b||!b.firstChild){var A=Error("Invalid caption track data");A.params=h;throw A;}if(b.firstChild.tagName==="timedtext"){if(Number(b.firstChild.getAttribute("format"))===3){r.N||(r.N=new Es(DEL(x),r.tT));p=m=r.N.Y(b,L);break b}var wX=Error("Unsupported subtitles format in web player (Format2)");
wX.params=h;throw wX;}if(b.firstChild.tagName==="transcript"){var qe=Error("Unsupported subtitles format in web player (Format1)");qe.params=h;throw qe;}var hG=Error("Invalid caption track data");hG.params=h;throw hG;}B=V.call(Q,p)}z=B}G=z}var jy=G;break a}catch(QZ){S.logger.N(187101178,"Captions parsing failed: "+QZ.message+". ");S.clear();jy=[];break a}jy=void 0}X=jy;X.length>0&&(jy=this.W,this.FA(jy,!!jy,N_(this)?"g":this.T?"m":"s"));this.player.PZ(X,void 0,this.V==="LIVE"||this.V==="SABR_LIVE");
!this.T||this.DC||N_(this)||g.jJ(this.tT)||g.ZK(this.tT)||g.lP(this.tT)||this.tT.Mi==="shortspage"||this.player.isInline()||(g.Ax(this.SA),X=Pzo({rV:0,D1:5,dK:5,D8:2,textAlign:0,Cv:0,lang:"en"}),this.CO=[X],jy=["Click "," for settings"],this.BM||(Z=new g.XX(g.rc()),g.d(this,Z),this.BM=Z.element),Z=X.end-X.start,(H=g.II(this.W))&&this.CO.push(new K8(X.start,Z,0,X.id,H)),this.CO.push(new K8(X.start,Z,0,X.id,jy[0]),new K8(X.start,Z,0,X.id,this.BM,!0),new K8(X.start,Z,0,X.id,jy[1],!0)),this.player.PZ(this.CO),
g.DA(this.SA));!this.T||this.DC||N_(this)||(g.sB(this.tT)?Ay(this,!0):n8(this,!0),this.j&&(this.j.V=this.W),this.player.Ja());this.T=!1}};
g.P.onCueRangeEnter=function(G){this.QH.push(G);wM(this.IU)};
g.P.onCueRangeExit=function(G){g.Ev(this.QH,G);this.N instanceof L8&&this.N.J&&this.player.eN([G]);wM(this.IU)};
g.P.getCaptionWindowContainerId=function(){return this.J.element.id};
g.P.CLi=function(){ZAG(this,this.CO);this.CO=null};
g.P.hP=function(){var G=this;if(!this.As||!this.C){this.IU.stop();g.C7U(this.wb);this.QH.sort(g.f6);var X=this.QH;if(this.AT){var Q=g.xo(X,function(Z){return this.AT.indexOf(Z)===-1},this);
Q.length&&(X=Q)}X=g.e(X);for(Q=X.next();!Q.done;Q=X.next())QXo(this,Q.value);X=g.e(Object.entries(this.Yc));var R=X.next();for(Q={};!R.done;Q={zt:void 0,DI:void 0},R=X.next()){var S=g.e(R.value);R=S.next().value;S=S.next().value;Q.zt=R;Q.DI=S;this.wb[Q.zt]?(Q.DI.element.parentNode||(Q.DI instanceof dM||Q.DI instanceof F8||g.RB(this.Yc,function(Z){return function(H,w){w!==Z.zt&&H.W.params.rV===Z.DI.W.params.rV&&H.W.params.D1===Z.DI.W.params.D1&&H.W.params.dK===Z.DI.W.params.dK&&(H.dispose(),delete G.Yc[w]);
return w===Z.zt}}(Q),this),this.J.element.appendChild(Q.DI.element)),Q.DI.e6(this.wb[Q.zt])):(Q.DI.dispose(),delete this.Yc[Q.zt])}}};
g.P.iod=function(){ANd(this,{},!0);this.player.tS("captionssettingschanged")};
g.P.Qt=function(){var G=bR.t1;G={background:G.background,backgroundOpacity:G.backgroundOpacity,charEdgeStyle:G.charEdgeStyle,color:G.color,fontFamily:G.fontFamily,fontSizeIncrement:G.fontSizeIncrement,fontStyle:G.bold&&G.italic?3:G.bold?1:G.italic?2:0,textOpacity:G.textOpacity,windowColor:bR.windowColor,windowOpacity:bR.windowOpacity};var X=l8a()||{};X.background!=null&&(G.background=X.background);X.backgroundOverride!=null&&(G.backgroundOverride=X.backgroundOverride);X.backgroundOpacity!=null&&(G.backgroundOpacity=
X.backgroundOpacity);X.backgroundOpacityOverride!=null&&(G.backgroundOpacityOverride=X.backgroundOpacityOverride);X.charEdgeStyle!=null&&(G.charEdgeStyle=X.charEdgeStyle);X.charEdgeStyleOverride!=null&&(G.charEdgeStyleOverride=X.charEdgeStyleOverride);X.color!=null&&(G.color=X.color);X.colorOverride!=null&&(G.colorOverride=X.colorOverride);X.fontFamily!=null&&(G.fontFamily=X.fontFamily);X.fontFamilyOverride!=null&&(G.fontFamilyOverride=X.fontFamilyOverride);X.fontSizeIncrement!=null&&(G.fontSizeIncrement=
X.fontSizeIncrement);X.fontSizeIncrementOverride!=null&&(G.fontSizeIncrementOverride=X.fontSizeIncrementOverride);X.fontStyle!=null&&(G.fontStyle=X.fontStyle);X.fontStyleOverride!=null&&(G.fontStyleOverride=X.fontStyleOverride);X.textOpacity!=null&&(G.textOpacity=X.textOpacity);X.textOpacityOverride!=null&&(G.textOpacityOverride=X.textOpacityOverride);X.windowColor!=null&&(G.windowColor=X.windowColor);X.windowColorOverride!=null&&(G.windowColorOverride=X.windowColorOverride);X.windowOpacity!=null&&
(G.windowOpacity=X.windowOpacity);X.windowOpacityOverride!=null&&(G.windowOpacityOverride=X.windowOpacityOverride);return G};
g.P.aK=function(G,X){var Q={};Object.assign(Q,l8a());Object.assign(Q,G);ANd(this,Q,X);this.player.tS("captionssettingschanged")};
g.P.t9=function(){!this.C&&this.loaded&&(g.Gn(this.Yc,function(G,X){G.dispose();delete this.Yc[X]},this),this.hP())};
g.P.Zk=function(G,X){switch(G){case "fontSize":if(isNaN(X))break;G=g.pT(X,-2,4);this.aK({fontSizeIncrement:G});return G;case "reload":X&&!this.C&&$d(this,this.W,!0);break;case "stickyLoading":X!==void 0&&this.tT.T&&(g.sB(this.tT)?Ay(this,!!X):n8(this,!!X));break;case "track":return SnH(this,X);case "tracklist":return this.N?g.P1(g.JE(this.N.W,!(!X||!X.includeAsr)),function(Q){return g.dS(Q)}):[];
case "translationLanguages":return this.N?this.N.C.map(function(Q){return Object.assign({},Q)}):[];
case "sampleSubtitles":this.C||X===void 0||HAa(this,!!X);break;case "sampleSubtitlesCustomized":this.C||HAa(this,!!X,X);break;case "recommendedTranslationLanguages":return g.s4();case "defaultTranslationSourceTrackIndices":return this.N?this.N.T:[]}};
g.P.getOptions=function(){var G="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.tT.T&&G.push("stickyLoading");return G};
g.P.nW=function(){var G=this.W;if(this.U.XS("captions")){if(this.tT.G("html5_modify_caption_vss_logging")){var X;return(G=(X=this.videoData.mS)!=null?X:null)?{cc:g.mcX(G)}:{}}if(G)return X=G.vssId,G.translationLanguage&&X&&(X="t"+X+"."+g.WM(G)),{cc:X}}return{}};
g.P.EFT=function(){this.isSubtitlesOn()?(g.sB(this.tT)?Ay(this,!1):n8(this,!1),GsZ(this),$d(this,null,!0)):this.Tr()};
g.P.Tr=function(){var G=N_(this)||!this.W?Dv(this,!0):this.W;G&&this.Od(G.vssId,"m");this.isSubtitlesOn()||$d(this,N_(this)||!this.W?Dv(this,!0):this.W,!0)};
g.P.isSubtitlesOn=function(){return!!this.loaded&&!!this.W&&!N_(this)};
g.P.miC=function(){var G=N_(this);yw(this,G)?$d(this,this.getAudioTrack().N,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Mt()&&(this.T=!1,this.W=null,this.N&&(this.N.dispose(),this.N=null)),this.Jw()&&(G?$d(this,Dv(this,!1),!1):this.load()))};
g.P.gF=function(G){G&&(this.yH={top:G.top,right:G.right,bottom:G.bottom,left:G.left,width:1-G.left-G.right,height:1-G.top-G.bottom},this.J.element.style.top=this.yH.top*100+"%",this.J.element.style.left=this.yH.left*100+"%",this.J.element.style.width=this.yH.width*100+"%",this.J.element.style.height=this.yH.height*100+"%",this.J.element.style.position="absolute",G=RjZ(this))&&(this.J.element.style.width=G.width+"px",this.J.element.style.height=G.height+"px")};
g.P.onVideoDataChange=function(G,X){G==="newdata"&&(this.videoData=X,this.loaded&&this.unload(),this.T=!1,this.W=null,this.N&&(this.N.dispose(),this.N=null,this.player.tS("captionschanged",{})),this.Jw()&&this.load())};
g.P.getAudioTrack=function(){return this.player.getAudioTrack()};
g.P.GaA=function(){var G=this.U.EY();G&&!G.U_()&&G.zz();this.U.isFullscreen()?(this.C=this.Xm=!0,this.loaded&&this.lF()):(this.Xm=this.tT.controlsType==="3",this.C=Ne4(this));$d(this,this.W)};
g.P.DP=function(){var G,X,Q,R=(G=this.videoData.getPlayerResponse())==null?void 0:(X=G.captions)==null?void 0:(Q=X.playerCaptionsTracklistRenderer)==null?void 0:Q.openTranscriptCommand;R&&this.player.E_("innertubeCommand",R)};
g.P.FA=function(G,X,Q){var R=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,S="";G&&(S=G.vssId,S=S.replace(R,""));var Z="";G&&G.getId()&&(Z=G.getId()||"");G&&G.getXtags()&&(G=G.getXtags(),G=G.replace(R,""),Z=Z.concat(";"+G));this.U.FA(X?S:"",X?Z:"",Q)};
g.P.Od=function(G,X){G=(G||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");G.length>0&&this.U.Od(G,X)};g.ud("captions",naH);})(_yt_player);
