(function(g){var window=this;'use strict';var VlZ=function(G){G.publish("autonavvisibility")},ImS=function(G,X){G.E_("onAutonavCoundownStarted",X)},dxS=function(G){var X,Q,R;
return G==null?void 0:(X=G.playerOverlays)==null?void 0:(Q=X.playerOverlayRenderer)==null?void 0:(R=Q.autoplay)==null?void 0:R.playerOverlayAutoplayRenderer},S7=function(G){var X=G.Z(),Q=X.V;
g.f.call(this,{D:"a",X:"ytp-autonav-suggestion-card",L:{href:"{{url}}",target:Q?X.j:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},K:[{D:"div",aU:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],L:{style:"{{background}}"},K:[{D:"div",L:{"aria-label":"{{timestamp}}"},aU:["ytp-autonav-timestamp"],WM:"{{duration}}"},{D:"div",aU:["ytp-autonav-live-stamp"],WM:"Live"},{D:"div",
aU:["ytp-autonav-upcoming-stamp"],WM:"Upcoming"},{D:"div",X:"ytp-autonav-list-overlay",K:[{D:"div",X:"ytp-autonav-mix-text",WM:"Mix"},{D:"div",X:"ytp-autonav-mix-icon"}]}]},{D:"div",aU:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],WM:"{{title}}"},{D:"div",aU:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],WM:"{{author}}"},{D:"div",aU:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],WM:"{{views_and_publish_time}}"}]});this.U=G;this.suggestion=
null;this.N=Q;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},ZH=function(G,X){X=X===void 0?!1:X;
g.f.call(this,{D:"div",X:"ytp-autonav-endscreen-countdown-overlay"});var Q=this;this.J=X;this.cancelCommand=this.S=void 0;this.Y=0;this.container=new g.f({D:"div",X:"ytp-autonav-endscreen-countdown-container"});g.d(this,this.container);this.container.s_(this.element);X=G.Z();var R=X.V;this.U=G;this.suggestion=null;this.onVideoDataChange("newdata",this.U.getVideoData());this.B(G,"videodatachange",this.onVideoDataChange);this.N=new g.f({D:"div",X:"ytp-autonav-endscreen-upnext-container",L:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},K:[{D:"div",X:"ytp-autonav-endscreen-upnext-header"},{D:"div",X:"ytp-autonav-endscreen-upnext-alternative-header",WM:"{{autoplayAlternativeHeader}}"},{D:"a",X:"ytp-autonav-endscreen-link-container",L:{href:"{{url}}",target:R?X.j:""},K:[{D:"div",X:"ytp-autonav-endscreen-upnext-thumbnail",L:{style:"{{background}}"},K:[{D:"div",L:{"aria-label":"{{timestamp}}"},aU:["ytp-autonav-timestamp"],
WM:"{{duration}}"},{D:"div",aU:["ytp-autonav-live-stamp"],WM:"Live"},{D:"div",aU:["ytp-autonav-upcoming-stamp"],WM:"Upcoming"}]},{D:"div",X:"ytp-autonav-endscreen-video-info",K:[{D:"div",X:"ytp-autonav-endscreen-premium-badge"},{D:"div",X:"ytp-autonav-endscreen-upnext-title",WM:"{{title}}"},{D:"div",X:"ytp-autonav-endscreen-upnext-author",WM:"{{author}}"},{D:"div",X:"ytp-autonav-view-and-date",WM:"{{views_and_publish_time}}"},{D:"div",X:"ytp-autonav-author-and-view",WM:"{{author_and_views}}"}]}]}]});
g.d(this,this.N);this.N.s_(this.container.element);R||this.B(this.N.VH("ytp-autonav-endscreen-link-container"),"click",this.LN);this.U.createClientVe(this.container.element,this,115127);this.U.createClientVe(this.N.VH("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.f({D:"div",X:"ytp-autonav-overlay"});g.d(this,this.overlay);this.overlay.s_(this.container.element);this.W=new g.f({D:"div",X:"ytp-autonav-endscreen-button-container"});g.d(this,this.W);this.W.s_(this.container.element);
this.cancelButton=new g.f({D:"button",aU:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",X.G("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],L:{"aria-label":"Cancel autoplay"},WM:"Cancel"});g.d(this,this.cancelButton);this.cancelButton.s_(this.W.element);this.cancelButton.listen("click",this.Xn,this);this.U.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.f({D:"a",aU:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
X.G("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],L:{href:"{{url}}",role:"button","aria-label":"Play next video"},WM:"Play Now"});g.d(this,this.playButton);this.playButton.s_(this.W.element);this.playButton.listen("click",this.LN,this);this.U.createServerVe(this.playButton.element,this.playButton,!0);(X=this.U.getVideoData())&&WtH(this,X);this.V=new g.fU(function(){pYn(Q)},500);
g.d(this,this.V);this.T9();this.B(G,"autonavvisibility",this.T9);this.U.G("web_autonav_color_transition")&&(this.B(G,"autonavchange",this.wq),this.B(G,"onAutonavCoundownStarted",this.ZOC))},HN=function(G){var X=G.U.V5(!0,G.U.isFullscreen());
g.S_(G.container.element,"ytp-autonav-endscreen-small-mode",G.lT(X));g.S_(G.container.element,"ytp-autonav-endscreen-is-premium",!!G.suggestion&&!!G.suggestion.MIB);g.S_(G.U.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!G.U.VU());g.S_(G.U.getRootNode(),"countdown-running",G.pu());g.S_(G.container.element,"ytp-player-content",G.U.VU());g.DN(G.overlay.element,{width:X.width+"px"});if(!G.pu()){G.U.VU()?y5a(G,Math.round(fmL(G)/1E3)):y5a(G);X=!!G.suggestion&&!!G.suggestion.bX;var Q=G.U.VU()||
!X;g.S_(G.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!Q&&X);g.S_(G.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",Q&&!X);G.W.Ta(G.U.VU());g.S_(G.element,"ytp-enable-w2w-color-transitions",Dxo(G))}},pYn=function(G){var X=fmL(G),Q=Math,R=Q.min;
var S=G.Y?Date.now()-G.Y:0;Q=R.call(Q,S,X);y5a(G,Math.ceil((X-Q)/1E3));X-Q<=500&&G.pu()?G.select(!0):G.pu()&&G.V.start()},fmL=function(G){if(G.U.isFullscreen()){var X;
G=(X=G.U.getVideoData())==null?void 0:X.aA;return G===-1||G===void 0?8E3:G}return G.U.Dd()>=0?G.U.Dd():g.i2(G.U.Z().experiments,"autoplay_time")||1E4},WtH=function(G,X){X=X.getWatchNextResponse();
var Q,R;X=(Q=dxS(X))==null?void 0:(R=Q.nextButton)==null?void 0:R.buttonRenderer;G.S=X==null?void 0:X.navigationEndpoint;Q=X==null?void 0:X.trackingParams;G.playButton&&Q&&G.U.setTrackingParams(G.playButton.element,Q)},Dxo=function(G){var X;
return!((X=G.U.getVideoData())==null||!X.watchToWatchTransitionRenderer)},y5a=function(G,X){X=X===void 0?-1:X;
G=G.N.VH("ytp-autonav-endscreen-upnext-header");g.Pq(G);if(X>=0){X=String(X);var Q="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],R="Up next in $SECONDS".indexOf(Q);if(R>=0){G.appendChild(g.oL("Up next in $SECONDS".slice(0,R)));var S=g.ml("span");g.Jx(S,"ytp-autonav-endscreen-upnext-header-countdown-number");g.ee(S,X);G.appendChild(S);G.appendChild(g.oL("Up next in $SECONDS".slice(R+Q.length)));return}}g.ee(G,"Up next")},qu=function(G,X){g.f.call(this,{D:"div",
aU:["html5-endscreen","ytp-player-content",X||"base-endscreen"]});this.created=!1;this.player=G},wY=function(G){g.f.call(this,{D:"div",
aU:["ytp-upnext","ytp-player-content"],L:{"aria-label":"{{aria_label}}"},K:[{D:"div",X:"ytp-cued-thumbnail-overlay-image",L:{style:"{{background}}"}},{D:"span",X:"ytp-upnext-top",K:[{D:"span",X:"ytp-upnext-header",WM:"Up Next"},{D:"span",X:"ytp-upnext-title",WM:"{{title}}"},{D:"span",X:"ytp-upnext-author",WM:"{{author}}"}]},{D:"a",X:"ytp-upnext-autoplay-icon",L:{role:"button",href:"{{url}}","aria-label":"Play next video"},K:[{D:"svg",L:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
K:[{D:"circle",X:"ytp-svg-autoplay-circle",L:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",X:"ytp-svg-autoplay-ring",L:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",X:"ytp-svg-fill",L:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",X:"ytp-upnext-bottom",K:[{D:"span",X:"ytp-upnext-cancel"},{D:"span",X:"ytp-upnext-paused",
WM:"Autoplay is paused"}]}]});this.api=G;this.cancelButton=null;this.S=this.VH("ytp-svg-autoplay-ring");this.Y=this.notification=this.N=this.suggestion=null;this.V=new g.fU(this.MC,5E3,this);this.W=0;var X=this.VH("ytp-upnext-cancel");this.cancelButton=new g.f({D:"button",aU:["ytp-upnext-cancel-button","ytp-button"],L:{tabindex:"0","aria-label":"Cancel autoplay"},WM:"Cancel"});g.d(this,this.cancelButton);this.cancelButton.listen("click",this.EV,this);this.cancelButton.s_(X);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.d(this,this.V);this.api.createClientVe(this.element,this,18788);X=this.VH("ytp-upnext-autoplay-icon");this.B(X,"click",this.Bj);this.api.createClientVe(X,this,115130);this.mJ();this.B(G,"autonavvisibility",this.mJ);this.B(G,"mdxnowautoplaying",this.i7U);this.B(G,"mdxautoplaycanceled",this.JsH);g.S_(this.element,"ytp-upnext-mobile",this.api.Z().W)},NJO=function(G,X){if(X)return X;
if(G.api.isFullscreen()){var Q;G=(Q=G.api.getVideoData())==null?void 0:Q.aA;return G===-1||G===void 0?8E3:G}return G.api.Dd()>=0?G.api.Dd():g.i2(G.api.Z().experiments,"autoplay_time")||1E4},A5L=function(G,X){X=NJO(G,X);
var Q=Math,R=Q.min;var S=(0,g.TB)()-G.W;Q=R.call(Q,S,X);X=X===0?1:Math.min(Q/X,1);G.S.setAttribute("stroke-dashoffset",""+-211*(X+1));X>=1&&G.pu()&&G.api.getPresentingPlayerType()!==3?G.select(!0):G.pu()&&G.N.start()},ha=function(G){qu.call(this,G,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.f({D:"div",X:"ytp-suggestion-panel",K:[{D:"div",aU:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],WM:"More videos"}]});this.T=new g.f({D:"div",X:"ytp-suggestions-container"});this.videos=[];this.Y=null;this.S=this.J=!1;this.W=new ZH(this.player);g.d(this,this.W);this.W.s_(this.element);G.getVideoData().kS?this.N=this.W:(this.N=new wY(G),g.$6(this.player,this.N.element,4),g.d(this,this.N));this.overlay=new g.f({D:"div",
X:"ytp-autonav-overlay-cancelled-state"});g.d(this,this.overlay);this.overlay.s_(this.element);this.V=new g.KP(this);g.d(this,this.V);g.d(this,this.table);this.table.s_(this.element);this.table.show();g.d(this,this.T);this.T.s_(this.table.element);this.hide()},L2=function(G){var X=G.VU();
X!==G.S&&(G.S=X,VlZ(G.player),G.S?(G.W!==G.N&&G.W.hide(),G.table.hide()):(G.W!==G.N&&G.W.show(),G.table.show()))},noH=function(G){qu.call(this,G,"videowall-endscreen");
var X=this;this.U=G;this.stills=[];this.Y=this.videoData=null;this.V=this.J=!1;this.T=null;g.Gk(this.element,"modern-videowall-endscreen");this.W=new g.KP(this);g.d(this,this.W);this.S=new g.fU(function(){g.Gk(X.element,"ytp-show-tiles")},0);
g.d(this,this.S);this.table=new g.XX({D:"div",X:"ytp-modern-endscreen-content"});g.d(this,this.table);this.table.s_(this.element);G.getVideoData().kS?this.N=new ZH(G,!0):this.N=new wY(G);g.d(this,this.N);g.$6(this.player,this.N.element,4);G.createClientVe(this.element,this,158789);this.hide()},kZ=function(G){return g.bG(G.player)&&G.wX()&&!G.Y},YZ=function(G){var X=G.VU();
X!==G.J&&(G.J=X,VlZ(G.player))},$xG=function(G){qu.call(this,G,"subscribecard-endscreen");
this.N=new g.f({D:"div",X:"ytp-subscribe-card",K:[{D:"img",X:"ytp-author-image",L:{src:"{{profilePicture}}"}},{D:"div",X:"ytp-subscribe-card-right",K:[{D:"div",X:"ytp-author-name",WM:"{{author}}"},{D:"div",X:"html5-subscribe-button-container"}]}]});g.d(this,this.N);this.N.s_(this.element);var X=G.getVideoData();this.subscribeButton=new g.J_("Subscribe",null,"Unsubscribe",null,!0,!1,X.F6,X.subscribed,"trailer-endscreen",null,G,!1);g.d(this,this.subscribeButton);this.subscribeButton.s_(this.N.VH("html5-subscribe-button-container"));
this.B(G,"videodatachange",this.GT);this.GT();this.hide()},j7=function(G){var X=G.Z(),Q=g.un||g.b$?{style:"will-change: opacity"}:void 0,R=X.V,S=["ytp-videowall-still"];
X.W&&S.push("ytp-videowall-show-text");g.f.call(this,{D:"a",aU:S,L:{href:"{{url}}",target:R?X.j:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{D:"div",X:"ytp-videowall-still-image",L:{style:"{{background}}"}},{D:"span",X:"ytp-videowall-still-info",L:{"aria-hidden":"true"},K:[{D:"span",X:"ytp-videowall-still-info-bg",K:[{D:"span",X:"ytp-videowall-still-info-content",L:Q,K:[{D:"span",X:"ytp-videowall-still-info-title",WM:"{{title}}"},
{D:"span",X:"ytp-videowall-still-info-author",WM:"{{author_and_views}}"},{D:"span",X:"ytp-videowall-still-info-live",WM:"Live"},{D:"span",X:"ytp-videowall-still-info-duration",WM:"{{duration}}"}]}]}]},{D:"span",aU:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],L:{"aria-hidden":"true"},K:[{D:"span",X:"ytp-videowall-still-listlabel-icon"},"Playlist",{D:"span",X:"ytp-videowall-still-listlabel-length",K:[" (",{D:"span",WM:"{{playlist_length}}"},")"]}]},{D:"span",aU:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],L:{"aria-hidden":"true"},K:[{D:"span",X:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{D:"span",X:"ytp-videowall-still-listlabel-length",WM:" (50+)"}]}]});this.suggestion=null;this.W=R;this.api=G;this.N=new g.KP(this);g.d(this,this.N);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.N.B(G,"videodatachange",this.onVideoDataChange);G.createServerVe(this.element,this);this.onVideoDataChange()},Mu=function(G){qu.call(this,G,"videowall-endscreen");
var X=this;this.U=G;this.Y=0;this.stills=[];this.V=this.videoData=null;this.S=this.T=!1;this.j=null;this.W=new g.KP(this);g.d(this,this.W);this.J=new g.fU(function(){g.Gk(X.element,"ytp-show-tiles")},0);
g.d(this,this.J);var Q=new g.f({D:"button",aU:["ytp-button","ytp-endscreen-previous"],L:{"aria-label":"Previous"},K:[g.LD()]});g.d(this,Q);Q.s_(this.element);Q.listen("click",this.fF,this);this.table=new g.XX({D:"div",X:"ytp-endscreen-content"});g.d(this,this.table);this.table.s_(this.element);Q=new g.f({D:"button",aU:["ytp-button","ytp-endscreen-next"],L:{"aria-label":"Next"},K:[g.kC()]});g.d(this,Q);Q.s_(this.element);Q.listen("click",this.jw,this);G.getVideoData().kS?this.N=new ZH(G,!0):this.N=
new wY(G);g.d(this,this.N);g.$6(this.player,this.N.element,4);G.createClientVe(this.element,this,158789);this.hide()},mm=function(G){return g.bG(G.player)&&G.wX()&&!G.V},ou=function(G){var X=G.VU();
X!==G.T&&(G.T=X,VlZ(G.player))},bAd=function(G,X){g.f.call(this,{D:"button",
aU:["ytp-watch-on-youtube-button","ytp-button"],WM:"{{content}}"});this.U=G;this.buttonType=this.buttonType=X;this.yW();this.buttonType===2&&g.Gk(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.yW);this.Ta(!0)},uk=function(G){qu.call(this,G,"watch-again-on-youtube-endscreen");
this.watchButton=new bAd(G,1);g.d(this,this.watchButton);this.watchButton.s_(this.element);g.CLS(G)&&(this.N=new g.nW(G),g.d(this,this.N),this.W=new g.f({D:"div",aU:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],L:{tabIndex:"-1"},K:[this.N]}),g.d(this,this.W),this.N.s_(this.W.element),this.W.s_(this.element));G.createClientVe(this.element,this,156914);this.hide()},GHa=function(G){g.P6.call(this,G);
var X=this;this.endScreen=null;this.N=this.W=this.Y=!1;this.listeners=new g.KP(this);g.d(this,this.listeners);var Q=G.Z();G.isEmbedsShortsMode()?this.endScreen=new uk(G):voH(G)?(this.Y=!0,J53(this),this.N?this.endScreen=new ha(G):Q.G("delhi_modern_endscreen")?this.endScreen=new noH(G):this.endScreen=new Mu(G)):Q.rS?this.endScreen=new $xG(G):this.endScreen=new qu(G);g.d(this,this.endScreen);g.$6(G,this.endScreen.element,4);iAv(this);this.listeners.B(G,"videodatachange",this.onVideoDataChange,this);
this.listeners.B(G,g.Dy("endscreen"),function(R){X.onCueRangeEnter(R)});
this.listeners.B(G,g.N3("endscreen"),function(R){X.onCueRangeExit(R)})},J53=function(G){var X=G.player.getVideoData();
if(!X||G.N===X.m4&&G.W===X.kS)return!1;G.N=X.m4;G.W=X.kS;return!0},voH=function(G){G=G.Z();
return G.kS&&!G.rS&&!G.disableOrganicUi},iAv=function(G){G.player.lf("endscreen");
var X=G.player.getVideoData();X=new g.yG(Math.max((X.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var Q=new g.yG(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});G.player.PZ([X,Q])};
g.WP.prototype.Dd=g.Sy(6,function(){return this.app.Dd()});
g.Y9.prototype.Dd=g.Sy(5,function(){return this.getVideoData().k8});
g.tL.prototype.kZ=g.Sy(4,function(G){this.sG().kZ(G)});
g.Df.prototype.kZ=g.Sy(3,function(G){this.fK!==G&&(this.fK=G,this.Ol())});
g.T(S7,g.f);S7.prototype.select=function(){this.U.mZ(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.QS||void 0)&&this.U.logClick(this.element)};
S7.prototype.onClick=function(G){g.ej(G,this.U,this.N,this.suggestion.sessionData||void 0)&&this.select()};
S7.prototype.onKeyPress=function(G){switch(G.keyCode){case 13:case 32:G.defaultPrevented||(this.select(),G.preventDefault())}};g.T(ZH,g.f);g.P=ZH.prototype;g.P.vP=function(G){this.suggestion!==G&&(this.suggestion=G,g.Su(this.N,G),this.playButton.updateValue("url",this.suggestion.Iu()),HN(this))};
g.P.pu=function(){return this.Y>0};
g.P.e4=function(){this.pu()||(this.Y=Date.now(),pYn(this),ImS(this.U,fmL(this)),g.S_(this.U.getRootNode(),"countdown-running",this.pu()))};
g.P.Mw=function(){this.bA();pYn(this);var G=this.N.VH("ytp-autonav-endscreen-upnext-header");G&&g.ee(G,"Up next")};
g.P.bA=function(){this.pu()&&(this.V.stop(),this.Y=0)};
g.P.select=function(G){this.U.nextVideo(!1,G===void 0?!1:G);this.bA()};
g.P.LN=function(G){g.ej(G,this.U)&&(G.currentTarget===this.playButton.element?this.U.logClick(this.playButton.element):G.currentTarget===this.N.VH("ytp-autonav-endscreen-link-container")&&(G=this.N.VH("ytp-autonav-endscreen-link-container"),this.U.logVisibility(G,!0),this.U.logClick(G)),this.S?(this.U.E_("innertubeCommand",this.S),this.bA()):this.select())};
g.P.Xn=function(){this.U.logClick(this.cancelButton.element);g.yY(this.U,!0);this.cancelCommand&&this.U.E_("innertubeCommand",this.cancelCommand)};
g.P.onVideoDataChange=function(G,X){WtH(this,X);G=X.getWatchNextResponse();var Q,R;G=(Q=dxS(G))==null?void 0:(R=Q.cancelButton)==null?void 0:R.buttonRenderer;this.cancelCommand=G==null?void 0:G.command};
g.P.ZOC=function(G){if(Dxo(this)){var X=this.U.getVideoData().watchToWatchTransitionRenderer,Q=X==null?void 0:X.fromColorPaletteDark;X=X==null?void 0:X.toColorPaletteDark;if(Q&&X){var R=this.element;R.style.setProperty("--w2w-start-background-color",g.BV(Q.surgeColor));R.style.setProperty("--w2w-start-primary-text-color",g.BV(Q.primaryTitleColor));R.style.setProperty("--w2w-start-secondary-text-color",g.BV(Q.secondaryTitleColor));R.style.setProperty("--w2w-end-background-color",g.BV(X.surgeColor));
R.style.setProperty("--w2w-end-primary-text-color",g.BV(X.primaryTitleColor));R.style.setProperty("--w2w-end-secondary-text-color",g.BV(X.secondaryTitleColor));R.style.setProperty("--w2w-animation-duration",G+"ms")}g.S_(this.element,"ytp-w2w-animate",!0)}};
g.P.wq=function(G){this.U.G("web_autonav_color_transition")&&G!==2&&g.S_(this.element,"ytp-w2w-animate",!1)};
g.P.T9=function(){var G=this.U.VU();this.J&&this.rb!==G&&this.Ta(G);HN(this);this.U.logVisibility(this.container.element,G);this.U.logVisibility(this.cancelButton.element,G);this.U.logVisibility(this.N.VH("ytp-autonav-endscreen-link-container"),G);this.U.logVisibility(this.playButton.element,G)};
g.P.lT=function(G){return G.width<400||G.height<459};g.T(qu,g.f);g.P=qu.prototype;g.P.create=function(){this.created=!0};
g.P.destroy=function(){this.created=!1};
g.P.wX=function(){return!1};
g.P.VU=function(){return!1};
g.P.RB=function(){return!1};g.T(wY,g.f);g.P=wY.prototype;g.P.MC=function(){this.notification&&(this.V.stop(),this.Ds(this.Y),this.Y=null,this.notification.close(),this.notification=null)};
g.P.vP=function(G){this.suggestion=G;g.Su(this,G,"hqdefault.jpg")};
g.P.mJ=function(){this.Ta(this.api.VU());this.api.logVisibility(this.element,this.api.VU());this.api.logVisibility(this.VH("ytp-upnext-autoplay-icon"),this.api.VU());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.VU())};
g.P.Bhm=function(){window.focus();this.MC()};
g.P.e4=function(G){var X=this;this.pu()||(g.ve("a11y-announce","Up Next "+this.suggestion.title),this.W=(0,g.TB)(),this.N=new g.fU(function(){A5L(X,G)},25),A5L(this,G),ImS(this.api,NJO(this,G)));
g.QD(this.element,"ytp-upnext-autoplay-paused")};
g.P.hide=function(){g.f.prototype.hide.call(this)};
g.P.pu=function(){return!!this.N};
g.P.Mw=function(){this.bA();this.W=(0,g.TB)();A5L(this);g.Gk(this.element,"ytp-upnext-autoplay-paused")};
g.P.bA=function(){this.pu()&&(this.N.dispose(),this.N=null)};
g.P.select=function(G){G=G===void 0?!1:G;if(this.api.Z().G("autonav_notifications")&&G&&window.Notification&&typeof document.hasFocus==="function"){var X=Notification.permission;X==="default"?Notification.requestPermission():X!=="granted"||document.hasFocus()||(this.MC(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.yJ()}),this.Y=this.B(this.notification,"click",this.Bhm),this.V.start())}this.bA();this.api.nextVideo(!1,G)};
g.P.Bj=function(G){!g.Ks(this.cancelButton.element,G.target)&&g.ej(G,this.api)&&(this.api.VU()&&this.api.logClick(this.VH("ytp-upnext-autoplay-icon")),this.select())};
g.P.EV=function(){this.api.VU()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.yY(this.api,!0)};
g.P.i7U=function(G){this.api.getPresentingPlayerType();this.show();this.e4(G)};
g.P.JsH=function(){this.api.getPresentingPlayerType();this.bA();this.hide()};
g.P.zT=function(){this.bA();this.MC();g.f.prototype.zT.call(this)};g.T(ha,qu);g.P=ha.prototype;g.P.create=function(){qu.prototype.create.call(this);this.V.B(this.player,"appresize",this.Sq);this.V.B(this.player,"onVideoAreaChange",this.Sq);this.V.B(this.player,"videodatachange",this.onVideoDataChange);this.V.B(this.player,"autonavchange",this.Zy);this.V.B(this.player,"onAutonavCancelled",this.Tm);this.onVideoDataChange()};
g.P.show=function(){qu.prototype.show.call(this);(this.J||this.Y&&this.Y!==this.videoData.clientPlaybackNonce)&&g.yY(this.player,!1);g.bG(this.player)&&this.wX()&&!this.Y?(L2(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.N.select(!0):this.N.e4():this.videoData.autonavState===3&&this.N.Mw()):(g.yY(this.player,!0),L2(this));this.Sq()};
g.P.hide=function(){qu.prototype.hide.call(this);this.N.Mw();L2(this)};
g.P.Sq=function(){var G=this.player.V5(!0,this.player.isFullscreen());L2(this);HN(this.W);g.S_(this.element,"ytp-autonav-cancelled-small-mode",this.lT(G));g.S_(this.element,"ytp-autonav-cancelled-tiny-mode",this.d1(G));g.S_(this.element,"ytp-autonav-cancelled-mini-mode",G.width<=400||G.height<=360);this.overlay&&g.DN(this.overlay.element,{width:G.width+"px"});if(!this.S)for(G=0;G<this.videos.length;G++)g.S_(this.videos[G].element,"ytp-suggestion-card-with-margin",G%2===1)};
g.P.onVideoDataChange=function(){var G=this.player.getVideoData();if(this.videoData!==G&&G){this.videoData=G;if((G=this.videoData.suggestions)&&G.length||this.player.G("web_player_autonav_empty_suggestions_fix")){var X=g.KL(this.videoData);X&&(this.N.vP(X),this.N!==this.W&&this.W.vP(X))}if(G&&G.length)for(X=0;X<Xk3.length;++X){var Q=Xk3[X];if(G&&G[Q]){this.videos[X]=new S7(this.player);var R=this.videos[X];Q=G[Q];R.suggestion!==Q&&(R.suggestion=Q,g.Su(R,Q));g.d(this,this.videos[X]);this.videos[X].s_(this.T.element)}}this.Sq()}};
g.P.Zy=function(G){G===1?(this.J=!1,this.Y=this.videoData.clientPlaybackNonce,this.N.bA(),this.rb&&this.Sq()):(this.J=!0,this.VU()&&(G===2?this.N.e4():G===3&&this.N.Mw()))};
g.P.Tm=function(G){G?this.Zy(1):(this.Y=null,this.J=!1)};
g.P.wX=function(){return this.videoData.autonavState!==1};
g.P.lT=function(G){return(G.width<910||G.height<459)&&!this.d1(G)&&!(G.width<=400||G.height<=360)};
g.P.d1=function(G){return G.width<800&&!(G.width<=400||G.height<=360)};
g.P.VU=function(){return this.rb&&g.bG(this.player)&&this.wX()&&!this.Y};
var Xk3=[1,3,2,4];g.T(noH,qu);g.P=noH.prototype;g.P.create=function(){qu.prototype.create.call(this);var G=this.player.getVideoData();G&&(this.videoData=G);this.yV();this.W.B(this.player,"appresize",this.yV);this.W.B(this.player,"onVideoAreaChange",this.yV);this.W.B(this.player,"videodatachange",this.onVideoDataChange);this.W.B(this.player,"autonavchange",this.Iz);this.W.B(this.player,"onAutonavCancelled",this.LF);G=this.videoData.autonavState;G!==this.T&&this.Iz(G);this.W.B(this.element,"transitionend",this.Z4)};
g.P.destroy=function(){g.e8(this.W);g.Q0(this.stills);this.stills=[];qu.prototype.destroy.call(this);g.QD(this.element,"ytp-show-tiles");this.S.stop();this.T=this.videoData.autonavState};
g.P.wX=function(){return this.videoData.autonavState!==1};
g.P.show=function(){var G=this.rb;qu.prototype.show.call(this);g.QD(this.element,"ytp-show-tiles");this.player.Z().W?g.NO(this.S):this.S.start();(this.V||this.Y&&this.Y!==this.videoData.clientPlaybackNonce)&&g.yY(this.player,!1);kZ(this)?(YZ(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.N.select(!0):this.N.e4():this.videoData.autonavState===3&&this.N.Mw()):(g.yY(this.player,!0),YZ(this));G!==this.rb&&this.player.logVisibility(this.element,!0)};
g.P.hide=function(){var G=this.rb;qu.prototype.hide.call(this);this.N.Mw();YZ(this);G!==this.rb&&this.player.logVisibility(this.element,!1)};
g.P.Z4=function(G){G.target===this.element&&this.yV()};
g.P.yV=function(){var G,X,Q,R;var S=((G=this.videoData)==null?0:(X=G.suggestions)==null?0:X.length)?(Q=this.videoData)==null?void 0:Q.suggestions:[(R=this.videoData)==null?void 0:g.KL(R)];if(S.length){X=this.U.V5(!0,this.U.isFullscreen());G=Math.floor((X.width-64+16)/(g.pT(X.width*.27,250,450)+16));X=Math.min(3,Math.floor((X.height-64)/((X.width-64-(G-1)*16)/G*.5625+70)));g.Rt(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.Gk(this.element,"ytp-modern-endscreen-limit-rows-"+X);g.S_(this.element,"ytp-modern-endscreen-single-item",G===1);g.S_(this.element,"ytp-modern-endscreen-row-0",X===0);G=this.table.element;G.ariaLive="polite";this.N.vP(g.KL(this.videoData));this.N instanceof ZH&&HN(this.N);g.S_(this.element,"ytp-endscreen-takeover",kZ(this));YZ(this);X=0;G.ariaBusy="true";Q=S.length;for(R=0;R<Q;R++){var Z=R%Q,H=this.stills[R];H||(H=new g.Zf(this.player),this.stills[R]=H,G.appendChild(H.element));g.FCe(H,S[Z]);X++}this.stills.length=
X}};
g.P.onVideoDataChange=function(){var G=this.player.getVideoData(1);this.videoData!==G&&(G!=null&&g.KL(G)?(this.videoData=G,this.yV()):this.player.Ni("missg",{vid:(G==null?void 0:G.videoId)||"",cpn:(G==null?void 0:G.clientPlaybackNonce)||""}))};
g.P.RB=function(){return this.N.pu()};
g.P.Iz=function(G){G===1?(this.V=!1,this.Y=this.videoData.clientPlaybackNonce,this.N.bA(),this.rb&&this.yV()):(this.V=!0,this.rb&&kZ(this)&&(G===2?this.N.e4():G===3&&this.N.Mw()))};
g.P.LF=function(G){if(G){for(G=0;G<this.stills.length;G++)this.U.logVisibility(this.stills[G].element,!0);this.Iz(1)}else this.Y=null,this.V=!1;this.yV()};
g.P.VU=function(){return this.rb&&kZ(this)};g.T($xG,qu);$xG.prototype.GT=function(){var G=this.player.getVideoData();this.N.update({profilePicture:G.profilePicture,author:G.author});this.subscribeButton.channelId=G.F6;var X=this.subscribeButton;G.subscribed?X.N():X.W()};g.T(j7,g.f);j7.prototype.select=function(){this.api.mZ(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.QS||void 0)&&this.api.logClick(this.element)};
j7.prototype.onClick=function(G){if(g.Jn(this.api.Z())&&this.api.G("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var X=this.suggestion.Iu(),Q={};g.NY(this.api,Q);X=g.on(X,Q);g.rU(X,this.api,G)}else g.ej(G,this.api,this.W,this.suggestion.sessionData||void 0)&&this.select()};
j7.prototype.onKeyPress=function(G){switch(G.keyCode){case 13:case 32:G.defaultPrevented||(this.select(),G.preventDefault())}};
j7.prototype.onVideoDataChange=function(){var G=this.api.getVideoData(),X=this.api.Z();this.W=G.KY?!1:X.V};g.T(Mu,qu);g.P=Mu.prototype;g.P.create=function(){qu.prototype.create.call(this);var G=this.player.getVideoData();G&&(this.videoData=G);this.jC();this.W.B(this.player,"appresize",this.jC);this.W.B(this.player,"onVideoAreaChange",this.jC);this.W.B(this.player,"videodatachange",this.onVideoDataChange);this.W.B(this.player,"autonavchange",this.oz);this.W.B(this.player,"onAutonavCancelled",this.KF);G=this.videoData.autonavState;G!==this.j&&this.oz(G);this.W.B(this.element,"transitionend",this.gq)};
g.P.destroy=function(){g.e8(this.W);g.Q0(this.stills);this.stills=[];qu.prototype.destroy.call(this);g.QD(this.element,"ytp-show-tiles");this.J.stop();this.j=this.videoData.autonavState};
g.P.wX=function(){return this.videoData.autonavState!==1};
g.P.show=function(){var G=this.rb;qu.prototype.show.call(this);g.QD(this.element,"ytp-show-tiles");this.player.Z().W?g.NO(this.J):this.J.start();(this.S||this.V&&this.V!==this.videoData.clientPlaybackNonce)&&g.yY(this.player,!1);mm(this)?(ou(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.N.select(!0):this.N.e4():this.videoData.autonavState===3&&this.N.Mw()):(g.yY(this.player,!0),ou(this));G!==this.rb&&this.player.logVisibility(this.element,!0)};
g.P.hide=function(){var G=this.rb;qu.prototype.hide.call(this);this.N.Mw();ou(this);G!==this.rb&&this.player.logVisibility(this.element,!1)};
g.P.gq=function(G){G.target===this.element&&this.jC()};
g.P.jC=function(){var G,X,Q,R;var S=((G=this.videoData)==null?0:(X=G.suggestions)==null?0:X.length)?(Q=this.videoData)==null?void 0:Q.suggestions:[(R=this.videoData)==null?void 0:g.KL(R)];if(S.length){g.Gk(this.element,"ytp-endscreen-paginate");var Z=this.U.V5(!0,this.U.isFullscreen());if(G=g.Ua(this.U))G=G.Yu()?48:32,Z.width-=G*2;var H=Z.width/Z.height;R=96/54;X=G=2;var w=Math.max(Z.width/96,2),h=Math.max(Z.height/54,2);Q=S.length;var L=Q*4;for(L-=4;L>0&&(G<w||X<h);){var k=G/2,Y=X/2,M=G<=w-2&&L>=
Y*4,m=X<=h-2&&L>=k*4;if((k+1)/Y*R/H>H/(k/(Y+1)*R)&&m)L-=k*4,X+=2;else if(M)L-=Y*4,G+=2;else if(m)L-=k*4,X+=2;else break}R=!1;L>=12&&Q*4-L<=6&&(X>=4||G>=4)&&(R=!0);L=G*96;w=X*54;H=L/w<H?Z.height/w:Z.width/L;H=Math.min(H,2);L=Math.floor(Math.min(Z.width,L*H));w=Math.floor(Math.min(Z.height,w*H));Z=this.table.element;Z.ariaLive="polite";g.XD(Z,L,w);g.DN(Z,{marginLeft:L/-2+"px",marginTop:w/-2+"px"});this.N.vP(g.KL(this.videoData));this.N instanceof ZH&&HN(this.N);g.S_(this.element,"ytp-endscreen-takeover",
mm(this));ou(this);L+=4;w+=4;H=0;Z.ariaBusy="true";for(h=0;h<G;h++)for(k=0;k<X;k++)if(Y=H,m=0,R&&h>=G-2&&k>=X-2?m=1:k%2===0&&h%2===0&&(k<2&&h<2?k===0&&h===0&&(m=2):m=2),Y=g.yo(Y+this.Y,Q),m!==0){M=this.stills[H];M||(M=new j7(this.player),this.stills[H]=M,Z.appendChild(M.element));var u=Math.floor(w*k/X),r=Math.floor(L*h/G),x=Math.floor(w*(k+m)/X)-u-4,c=Math.floor(L*(h+m)/G)-r-4;g.vq(M.element,r,u);g.XD(M.element,c,x);g.DN(M.element,"transitionDelay",(k+h)/20+"s");g.S_(M.element,"ytp-videowall-still-mini",
m===1);g.S_(M.element,"ytp-videowall-still-large",m>2);m=Math.max(c,x);g.S_(M.element,"ytp-videowall-still-round-large",m>=256);g.S_(M.element,"ytp-videowall-still-round-medium",m>96&&m<256);g.S_(M.element,"ytp-videowall-still-round-small",m<=96);Y=S[Y];M.suggestion!==Y&&(M.suggestion=Y,m=M.api.Z(),u=g.iv(M.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.Su(M,Y,u),g.Jn(m)&&!M.api.G("web_player_log_click_before_generating_ve_conversion_params")&&(m=Y.Iu(),u={},g.x6(M.api,"addEmbedsConversionTrackingParams",
[u]),m=g.on(m,u),M.updateValue("url",m)),(Y=(Y=Y.sessionData)&&Y.itct)&&M.api.setTrackingParams(M.element,Y));H++}Z.ariaBusy="false";g.S_(this.element,"ytp-endscreen-paginate",H<Q);for(S=this.stills.length-1;S>=H;S--)G=this.stills[S],g.Tt(G.element),g.Xh(G);this.stills.length=H}};
g.P.onVideoDataChange=function(){var G=this.player.getVideoData(1);this.videoData!==G&&(G!=null&&g.KL(G)?(this.Y=0,this.videoData=G,this.jC()):this.player.Ni("missg",{vid:(G==null?void 0:G.videoId)||"",cpn:(G==null?void 0:G.clientPlaybackNonce)||""}))};
g.P.jw=function(){this.Y+=this.stills.length;this.jC()};
g.P.fF=function(){this.Y-=this.stills.length;this.jC()};
g.P.RB=function(){return this.N.pu()};
g.P.oz=function(G){G===1?(this.S=!1,this.V=this.videoData.clientPlaybackNonce,this.N.bA(),this.rb&&this.jC()):(this.S=!0,this.rb&&mm(this)&&(G===2?this.N.e4():G===3&&this.N.Mw()))};
g.P.KF=function(G){if(G){for(G=0;G<this.stills.length;G++)this.U.logVisibility(this.stills[G].element,!0);this.oz(1)}else this.V=null,this.S=!1;this.jC()};
g.P.VU=function(){return this.rb&&mm(this)};g.T(bAd,g.f);g.P=bAd.prototype;g.P.yW=function(){switch(this.buttonType){case 1:var G="Watch again on YouTube";var X=156915;break;case 2:G="Continue watching on YouTube";X=156942;break;default:G="Continue watching on YouTube",X=156942}this.update({content:G});this.U.hasVe(this.element)&&this.U.destroyVe(this.element);this.U.createClientVe(this.element,this,X)};
g.P.onClick=function(G){this.U.G("web_player_log_click_before_generating_ve_conversion_params")&&this.U.logClick(this.element);g.rU(this.getVideoUrl(),this.U,G);this.U.G("web_player_log_click_before_generating_ve_conversion_params")||this.U.logClick(this.element)};
g.P.getVideoUrl=function(){var G=!0;switch(this.buttonType){case 1:G=!0;break;case 2:G=!1}G=this.U.getVideoUrl(G,!1,!1,!0);var X=this.U.Z();if(g.Jn(X)){var Q={};g.Jn(X)&&g.x6(this.U,"addEmbedsConversionTrackingParams",[Q]);G=g.on(G,Q)}return G};
g.P.logVisibility=function(){this.U.logVisibility(this.element,this.rb&&this.C)};
g.P.show=function(){g.f.prototype.show.call(this);this.logVisibility()};
g.P.hide=function(){g.f.prototype.hide.call(this);this.logVisibility()};
g.P.ej=function(G){g.f.prototype.ej.call(this,G);this.logVisibility()};g.T(uk,qu);uk.prototype.hasSuggestions=function(){var G;return(G=this.N)==null?void 0:G.hasSuggestions()};
uk.prototype.show=function(){if(this.player.getPlayerState()!==3){qu.prototype.show.call(this);var G=this.W;if(G){var X=this.N.hasSuggestions();g.S_(this.element,"ytp-shorts-branded-ui",X);X?G.show():G.hide()}var Q;(Q=g.Ua(this.player))==null||Q.kZ(!0);this.player.logVisibility(this.element,!0);this.watchButton.ej(!0)}};
uk.prototype.hide=function(){qu.prototype.hide.call(this);var G;(G=g.Ua(this.player))==null||G.kZ(!1);this.player.logVisibility(this.element,!1);this.watchButton.ej(!1)};g.T(GHa,g.P6);g.P=GHa.prototype;g.P.Jw=function(){var G=this.player.getVideoData(),X=G.mutedAutoplay&&(G.limitedPlaybackDurationInSeconds>0||G.endSeconds>0||G.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!X)return!0;var Q;var R=!!((G==null?0:g.KL(G))||(G==null?0:(Q=G.suggestions)==null?0:Q.length));R=!voH(this.player)||R;G=G.F0;Q=this.player.xR();return R&&!G&&!Q&&!X};
g.P.VU=function(){return this.endScreen.VU()};
g.P.PB=function(){return this.VU()?this.endScreen.RB():!1};
g.P.zT=function(){this.player.lf("endscreen");g.P6.prototype.zT.call(this)};
g.P.load=function(){var G=this.player.getVideoData();var X=G.transitionEndpointAtEndOfStream;if(X&&X.videoId){var Q=this.player.p7().Kd.get("heartbeat"),R=g.KL(G);!R||X.videoId!==R.videoId||G.Yi?(this.player.mZ(X.videoId,void 0,void 0,!0,!0,X),Q&&Q.xE("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),G=!0):G=!1}else G=!1;G||(g.P6.prototype.load.call(this),this.endScreen.show())};
g.P.unload=function(){g.P6.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.P.onCueRangeEnter=function(G){this.Jw()&&(this.endScreen.created||this.endScreen.create(),G.getId()==="load"&&this.load())};
g.P.onCueRangeExit=function(G){G.getId()==="load"&&this.loaded&&this.unload()};
g.P.onVideoDataChange=function(){iAv(this);this.Y&&J53(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.N?this.endScreen=new ha(this.player):this.endScreen=new Mu(this.player),g.d(this,this.endScreen),g.$6(this.player,this.endScreen.element,4))};g.ud("endscreen",GHa);})(_yt_player);
